/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Library/work/workspace-my/github/document-backup/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-78aea302",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78aea302").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-75d716f2",
    path: "/blog/20210726-%E6%9E%B6%E6%9E%84%E6%A2%B3%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75d716f2").then(next)
    },
  },
  {
    path: "/blog/20210726-架构梳理.html",
    redirect: "/blog/20210726-%E6%9E%B6%E6%9E%84%E6%A2%B3%E7%90%86.html"
  },
  {
    path: "/blog/20210726-架构梳理.html",
    redirect: "/blog/20210726-%E6%9E%B6%E6%9E%84%E6%A2%B3%E7%90%86.html"
  },
  {
    name: "v-50c65d7c",
    path: "/blog/Database/DM/DM.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50c65d7c").then(next)
    },
  },
  {
    name: "v-9974b88c",
    path: "/blog/Database/MongoDB/MongoDB-Expression.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9974b88c").then(next)
    },
  },
  {
    name: "v-1da76794",
    path: "/blog/Database/MongoDB/MongoDB-Script.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1da76794").then(next)
    },
  },
  {
    name: "v-705c290a",
    path: "/blog/Database/MongoDB/MongoDB-Init.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-705c290a").then(next)
    },
  },
  {
    name: "v-4746da40",
    path: "/blog/Database/MongoDB/MongoDB-Wait.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4746da40").then(next)
    },
  },
  {
    name: "v-3b15c47c",
    path: "/blog/Database/Mysql/Mysql-Console.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b15c47c").then(next)
    },
  },
  {
    name: "v-c431ecc8",
    path: "/blog/Database/MongoDB/MongoDB-Shell.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c431ecc8").then(next)
    },
  },
  {
    name: "v-ba2109c8",
    path: "/blog/Database/Mysql/Mysql-Error.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba2109c8").then(next)
    },
  },
  {
    name: "v-3a2a80ca",
    path: "/blog/Database/Mysql/Mysql-Init.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a2a80ca").then(next)
    },
  },
  {
    name: "v-27cccf9c",
    path: "/blog/Database/Mysql/Mysql-SQL.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27cccf9c").then(next)
    },
  },
  {
    name: "v-de30d708",
    path: "/blog/Database/Mysql/Mysql-Workbench.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-de30d708").then(next)
    },
  },
  {
    name: "v-490cdd2e",
    path: "/blog/Database/Redis/Redis-Init.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-490cdd2e").then(next)
    },
  },
  {
    name: "v-9571fe88",
    path: "/blog/Java-Frame/IDE/IDEA-Wait.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9571fe88").then(next)
    },
  },
  {
    name: "v-fb277ca0",
    path: "/blog/Java-Frame/IDE/IDEA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fb277ca0").then(next)
    },
  },
  {
    name: "v-b2293f08",
    path: "/blog/Java-Frame/Log/Logback.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b2293f08").then(next)
    },
  },
  {
    name: "v-425dcf7c",
    path: "/blog/Java-Frame/Maven/Maven-Pom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-425dcf7c").then(next)
    },
  },
  {
    name: "v-d62d7168",
    path: "/blog/Java-Frame/Other/apollo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d62d7168").then(next)
    },
  },
  {
    name: "v-055faf62",
    path: "/blog/Java-Frame/Other/mq.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-055faf62").then(next)
    },
  },
  {
    name: "v-7ac3c9c8",
    path: "/blog/Java-Frame/Other/nacos.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ac3c9c8").then(next)
    },
  },
  {
    name: "v-40cfb7dc",
    path: "/blog/Java-Frame/Other/nginx.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40cfb7dc").then(next)
    },
  },
  {
    name: "v-4c2ae1b6",
    path: "/blog/Java-Frame/Quartz/Quartz-Database.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c2ae1b6").then(next)
    },
  },
  {
    name: "v-2bbefc94",
    path: "/blog/Java-Frame/Quartz/Quartz-Up.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2bbefc94").then(next)
    },
  },
  {
    name: "v-415c23fc",
    path: "/blog/Java-Frame/Spring/Spring-Event.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-415c23fc").then(next)
    },
  },
  {
    name: "v-7375ab7c",
    path: "/blog/Java-Frame/Spring/Spring-Transaction.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7375ab7c").then(next)
    },
  },
  {
    name: "v-1c5fea08",
    path: "/blog/Java-Frame/Spring/Spring-Validator.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c5fea08").then(next)
    },
  },
  {
    name: "v-2176b88e",
    path: "/blog/Java-Frame/SpringBoot/SpringBoot-Annotation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2176b88e").then(next)
    },
  },
  {
    name: "v-15f9730c",
    path: "/blog/Java-Frame/SpringBoot/SpringBoot-Init.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15f9730c").then(next)
    },
  },
  {
    name: "v-643efc08",
    path: "/blog/Java-Frame/SpringBoot/SpringBoot-Tool.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-643efc08").then(next)
    },
  },
  {
    name: "v-0485fdcc",
    path: "/blog/Java-Frame/Tomcat/Tomcat-Init.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0485fdcc").then(next)
    },
  },
  {
    name: "v-357e65bc",
    path: "/blog/Java-Frame/Tomcat/Tomcat-web.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-357e65bc").then(next)
    },
  },
  {
    name: "v-2d305b94",
    path: "/blog/Java/Annotation/Interface.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d305b94").then(next)
    },
  },
  {
    name: "v-705bcb48",
    path: "/blog/Java/Annotation/package-info.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-705bcb48").then(next)
    },
  },
  {
    name: "v-5c24bff4",
    path: "/blog/Java/Common/Common-file.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c24bff4").then(next)
    },
  },
  {
    name: "v-42965230",
    path: "/blog/Java/Common/Common-sort.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42965230").then(next)
    },
  },
  {
    name: "v-b11c2dc8",
    path: "/blog/Java/FastJson/Fastjson-Deserialize.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b11c2dc8").then(next)
    },
  },
  {
    name: "v-fcfeb5c8",
    path: "/blog/Java-Frame/SpringCloud/SpringCloud.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fcfeb5c8").then(next)
    },
  },
  {
    name: "v-58efd072",
    path: "/blog/Java/FastJson/Fastjson-JSONField-JSONType.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58efd072").then(next)
    },
  },
  {
    name: "v-01a4e188",
    path: "/blog/Java/FastJson/Fastjson-Serialize.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01a4e188").then(next)
    },
  },
  {
    name: "v-175d2bbc",
    path: "/blog/Java/FastJson/Fastjson-SerializeFilter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-175d2bbc").then(next)
    },
  },
  {
    name: "v-3f473688",
    path: "/blog/Java/FastJson/Fastjson-SerializerFeature.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f473688").then(next)
    },
  },
  {
    name: "v-f41999c8",
    path: "/blog/Java/FastJson/Fastjson-Use.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f41999c8").then(next)
    },
  },
  {
    name: "v-5ab3f0dc",
    path: "/blog/Java/Tool/Awesome-Java.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ab3f0dc").then(next)
    },
  },
  {
    name: "v-4e49d5fc",
    path: "/blog/Live-Stream/AR.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e49d5fc").then(next)
    },
  },
  {
    name: "v-2869547c",
    path: "/blog/Live-Stream/JavaCV.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2869547c").then(next)
    },
  },
  {
    name: "v-17a98614",
    path: "/blog/Live-Stream/SRS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17a98614").then(next)
    },
  },
  {
    name: "v-28d93450",
    path: "/blog/Live-Stream/WebSocket.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28d93450").then(next)
    },
  },
  {
    name: "v-3501a244",
    path: "/blog/Markdown/Markdown-Flowchart.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3501a244").then(next)
    },
  },
  {
    name: "v-58da28b8",
    path: "/blog/Markdown/Markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58da28b8").then(next)
    },
  },
  {
    name: "v-2ab4e8c8",
    path: "/blog/OS/Linux/Linux-Command.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ab4e8c8").then(next)
    },
  },
  {
    name: "v-e6029e38",
    path: "/blog/OS/Linux/Linux-Init.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e6029e38").then(next)
    },
  },
  {
    name: "v-e375a04c",
    path: "/blog/OS/Linux/Linux-Wait.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e375a04c").then(next)
    },
  },
  {
    name: "v-9d962bc8",
    path: "/blog/OS/Mac/Mac.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9d962bc8").then(next)
    },
  },
  {
    name: "v-207f6188",
    path: "/blog/OS/Other/Kylin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-207f6188").then(next)
    },
  },
  {
    name: "v-1efca2cc",
    path: "/blog/Operation-Maintenance/Docker/Docker-Jar.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1efca2cc").then(next)
    },
  },
  {
    name: "v-13907f22",
    path: "/blog/Operation-Maintenance/Docker/Docker-Shell.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13907f22").then(next)
    },
  },
  {
    name: "v-809091d4",
    path: "/blog/Other/Ngrok.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-809091d4").then(next)
    },
  },
  {
    name: "v-785f678c",
    path: "/blog/Testing/Test-Common/Blackbox-Whitebox.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-785f678c").then(next)
    },
  },
  {
    name: "v-edab2660",
    path: "/blog/Testing/Test-Common/Test-Assert.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-edab2660").then(next)
    },
  },
  {
    name: "v-160b5d5c",
    path: "/blog/Testing/TestNG/TestNG-Annotation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-160b5d5c").then(next)
    },
  },
  {
    name: "v-2950a8c8",
    path: "/blog/Testing/TestNG/TestNG-DataProvider.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2950a8c8").then(next)
    },
  },
  {
    name: "v-d23a1e88",
    path: "/blog/Testing/TestNG/TestNG-Init.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d23a1e88").then(next)
    },
  },
  {
    name: "v-ad67ce6c",
    path: "/blog/Web/CSS/CSS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ad67ce6c").then(next)
    },
  },
  {
    name: "v-2a32d3bc",
    path: "/blog/Web/Android/Reference.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a32d3bc").then(next)
    },
  },
  {
    name: "v-bec16b48",
    path: "/blog/Web/IDE/VSCode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bec16b48").then(next)
    },
  },
  {
    name: "v-7747d57c",
    path: "/blog/Web/JS/JS-Module-Specification.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7747d57c").then(next)
    },
  },
  {
    name: "v-bdb60688",
    path: "/blog/Web/JS/JS-Window.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bdb60688").then(next)
    },
  },
  {
    name: "v-d38cf784",
    path: "/blog/Web/Vue/Vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d38cf784").then(next)
    },
  },
  {
    name: "v-175829bc",
    path: "/blog/Web/Vue/Vuepress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-175829bc").then(next)
    },
  },
  {
    name: "v-04d8af08",
    path: "/blog/up_up_up.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04d8af08").then(next)
    },
  },
  {
    name: "v-da79eb82",
    path: "/blog/%E4%B8%B4%E6%97%B6%E5%AD%98%E5%82%A8/%E6%8A%93%E5%8C%85%E5%B7%A5%E5%85%B7%20Fiddler/Fiddler.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-da79eb82").then(next)
    },
  },
  {
    path: "/blog/临时存储/抓包工具 Fiddler/Fiddler.html",
    redirect: "/blog/%E4%B8%B4%E6%97%B6%E5%AD%98%E5%82%A8/%E6%8A%93%E5%8C%85%E5%B7%A5%E5%85%B7%20Fiddler/Fiddler.html"
  },
  {
    path: "/blog/临时存储/抓包工具 Fiddler/Fiddler.html",
    redirect: "/blog/%E4%B8%B4%E6%97%B6%E5%AD%98%E5%82%A8/%E6%8A%93%E5%8C%85%E5%B7%A5%E5%85%B7%20Fiddler/Fiddler.html"
  },
  {
    name: "v-d038b8de",
    path: "/blog/%E6%A6%82%E5%BF%B5%E6%A2%B3%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d038b8de").then(next)
    },
  },
  {
    path: "/blog/概念梳理.html",
    redirect: "/blog/%E6%A6%82%E5%BF%B5%E6%A2%B3%E7%90%86.html"
  },
  {
    path: "/blog/概念梳理.html",
    redirect: "/blog/%E6%A6%82%E5%BF%B5%E6%A2%B3%E7%90%86.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]