/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Library/work/workspace-my/github/document-backup/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-705c290a",
    path: "/blog/Database/MongoDB/MongoDB-Init.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-705c290a").then(next)
    },
  },
  {
    name: "v-78aea302",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78aea302").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-50c65d7c",
    path: "/blog/Database/DM/DM.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50c65d7c").then(next)
    },
  },
  {
    name: "v-1da76794",
    path: "/blog/Database/MongoDB/MongoDB-Script.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1da76794").then(next)
    },
  },
  {
    name: "v-c431ecc8",
    path: "/blog/Database/MongoDB/MongoDB-Shell.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c431ecc8").then(next)
    },
  },
  {
    name: "v-9974b88c",
    path: "/blog/Database/MongoDB/MongoDB-Expression.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9974b88c").then(next)
    },
  },
  {
    name: "v-4746da40",
    path: "/blog/Database/MongoDB/MongoDB-Wait.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4746da40").then(next)
    },
  },
  {
    name: "v-3a2a80ca",
    path: "/blog/Database/Mysql/Mysql-Init.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a2a80ca").then(next)
    },
  },
  {
    name: "v-ba2109c8",
    path: "/blog/Database/Mysql/Mysql-Error.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba2109c8").then(next)
    },
  },
  {
    name: "v-3b15c47c",
    path: "/blog/Database/Mysql/Mysql-Console.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b15c47c").then(next)
    },
  },
  {
    name: "v-38e9a780",
    path: "/blog/Database/Mysql/Mysql-Wait.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38e9a780").then(next)
    },
  },
  {
    name: "v-de30d708",
    path: "/blog/Database/Mysql/Mysql-Workbench.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-de30d708").then(next)
    },
  },
  {
    name: "v-490cdd2e",
    path: "/blog/Database/Redis/Redis-Init.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-490cdd2e").then(next)
    },
  },
  {
    name: "v-27cccf9c",
    path: "/blog/Database/Mysql/Mysql-SQL.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27cccf9c").then(next)
    },
  },
  {
    name: "v-5b405880",
    path: "/blog/Interview/Foremost/%E7%AE%80%E5%8E%86/%E7%AE%80%E5%8E%86%20%E6%A6%82%E8%A6%81%E8%AF%B4%E6%98%8E.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b405880").then(next)
    },
  },
  {
    path: "/blog/Interview/Foremost/简历/简历 概要说明.html",
    redirect: "/blog/Interview/Foremost/%E7%AE%80%E5%8E%86/%E7%AE%80%E5%8E%86%20%E6%A6%82%E8%A6%81%E8%AF%B4%E6%98%8E.html"
  },
  {
    path: "/blog/Interview/Foremost/简历/简历 概要说明.html",
    redirect: "/blog/Interview/Foremost/%E7%AE%80%E5%8E%86/%E7%AE%80%E5%8E%86%20%E6%A6%82%E8%A6%81%E8%AF%B4%E6%98%8E.html"
  },
  {
    name: "v-f5b84302",
    path: "/blog/Interview/Foremost/%E9%9D%A2%E8%AF%95%E9%97%AE%E9%A2%98/Linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f5b84302").then(next)
    },
  },
  {
    path: "/blog/Interview/Foremost/面试问题/Linux.html",
    redirect: "/blog/Interview/Foremost/%E9%9D%A2%E8%AF%95%E9%97%AE%E9%A2%98/Linux.html"
  },
  {
    path: "/blog/Interview/Foremost/面试问题/Linux.html",
    redirect: "/blog/Interview/Foremost/%E9%9D%A2%E8%AF%95%E9%97%AE%E9%A2%98/Linux.html"
  },
  {
    name: "v-5b280128",
    path: "/blog/Interview/Foremost/%E8%AF%9D%E6%9C%AF/%E8%87%AA%E6%88%91%E4%BB%8B%E7%BB%8D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b280128").then(next)
    },
  },
  {
    path: "/blog/Interview/Foremost/话术/自我介绍.html",
    redirect: "/blog/Interview/Foremost/%E8%AF%9D%E6%9C%AF/%E8%87%AA%E6%88%91%E4%BB%8B%E7%BB%8D.html"
  },
  {
    path: "/blog/Interview/Foremost/话术/自我介绍.html",
    redirect: "/blog/Interview/Foremost/%E8%AF%9D%E6%9C%AF/%E8%87%AA%E6%88%91%E4%BB%8B%E7%BB%8D.html"
  },
  {
    name: "v-47cc03e4",
    path: "/blog/Database/Redis/Redis-Wait.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47cc03e4").then(next)
    },
  },
  {
    name: "v-04a20994",
    path: "/blog/Interview/Foremost/%E9%A1%B9%E7%9B%AE%E4%BB%8B%E7%BB%8D/%E6%99%BA%E6%85%A7%E7%8E%AF%E5%8D%AB%E4%B8%9A%E5%8A%A1%E6%94%AF%E6%92%91%E7%B3%BB%E7%BB%9F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04a20994").then(next)
    },
  },
  {
    path: "/blog/Interview/Foremost/项目介绍/智慧环卫业务支撑系统.html",
    redirect: "/blog/Interview/Foremost/%E9%A1%B9%E7%9B%AE%E4%BB%8B%E7%BB%8D/%E6%99%BA%E6%85%A7%E7%8E%AF%E5%8D%AB%E4%B8%9A%E5%8A%A1%E6%94%AF%E6%92%91%E7%B3%BB%E7%BB%9F.html"
  },
  {
    path: "/blog/Interview/Foremost/项目介绍/智慧环卫业务支撑系统.html",
    redirect: "/blog/Interview/Foremost/%E9%A1%B9%E7%9B%AE%E4%BB%8B%E7%BB%8D/%E6%99%BA%E6%85%A7%E7%8E%AF%E5%8D%AB%E4%B8%9A%E5%8A%A1%E6%94%AF%E6%92%91%E7%B3%BB%E7%BB%9F.html"
  },
  {
    name: "v-49d57e1c",
    path: "/blog/Interview/Java/String-Stringbuffer-Stringbuiler.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49d57e1c").then(next)
    },
  },
  {
    name: "v-7544693c",
    path: "/blog/Interview/Java/Int-Integer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7544693c").then(next)
    },
  },
  {
    name: "v-5fe4e670",
    path: "/blog/Interview/Java/Collection.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fe4e670").then(next)
    },
  },
  {
    name: "v-4e419820",
    path: "/blog/Interview/Java/Thread.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e419820").then(next)
    },
  },
  {
    name: "v-fb277ca0",
    path: "/blog/Java-Frame/IDE/IDEA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fb277ca0").then(next)
    },
  },
  {
    name: "v-9571fe88",
    path: "/blog/Java-Frame/IDE/IDEA-Wait.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9571fe88").then(next)
    },
  },
  {
    name: "v-415c23fc",
    path: "/blog/Java-Frame/Spring/Spring-Event.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-415c23fc").then(next)
    },
  },
  {
    name: "v-2176b88e",
    path: "/blog/Java-Frame/SpringBoot/SpringBoot-Annotation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2176b88e").then(next)
    },
  },
  {
    name: "v-1c5fea08",
    path: "/blog/Java-Frame/Spring/Spring-Validator.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c5fea08").then(next)
    },
  },
  {
    name: "v-7375ab7c",
    path: "/blog/Java-Frame/Spring/Spring-Transaction.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7375ab7c").then(next)
    },
  },
  {
    name: "v-24a04378",
    path: "/blog/Java-Frame/SpringBoot/SpringBoot-Lombok.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24a04378").then(next)
    },
  },
  {
    name: "v-e4cffcfc",
    path: "/blog/Java-Frame/SpringBoot/SpringBoot-wait.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e4cffcfc").then(next)
    },
  },
  {
    name: "v-f2e4e27c",
    path: "/blog/Java-Frame/Spring/Spring-Wait.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f2e4e27c").then(next)
    },
  },
  {
    name: "v-357e65bc",
    path: "/blog/Java-Frame/Tomcat/Tomcat-web.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-357e65bc").then(next)
    },
  },
  {
    name: "v-0485fdcc",
    path: "/blog/Java-Frame/Tomcat/Tomcat-Init.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0485fdcc").then(next)
    },
  },
  {
    name: "v-12fea34a",
    path: "/blog/Java-Frame/apollo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12fea34a").then(next)
    },
  },
  {
    name: "v-0a9953c0",
    path: "/blog/Java-Frame/mq.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a9953c0").then(next)
    },
  },
  {
    name: "v-af354208",
    path: "/blog/Java-Frame/nacos.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-af354208").then(next)
    },
  },
  {
    name: "v-b1dc9f88",
    path: "/blog/Java-Frame/nginx.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b1dc9f88").then(next)
    },
  },
  {
    name: "v-fcfeb5c8",
    path: "/blog/Java-Frame/SpringCloud/SpringCloud.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fcfeb5c8").then(next)
    },
  },
  {
    name: "v-705bcb48",
    path: "/blog/Java/Annotation/package-info.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-705bcb48").then(next)
    },
  },
  {
    name: "v-58efd072",
    path: "/blog/Java/FastJson/Fastjson-JSONField-JSONType.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58efd072").then(next)
    },
  },
  {
    name: "v-3f473688",
    path: "/blog/Java/FastJson/Fastjson-SerializerFeature.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f473688").then(next)
    },
  },
  {
    name: "v-b11c2dc8",
    path: "/blog/Java/FastJson/Fastjson-Deserialize.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b11c2dc8").then(next)
    },
  },
  {
    name: "v-01a4e188",
    path: "/blog/Java/FastJson/Fastjson-Serialize.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01a4e188").then(next)
    },
  },
  {
    name: "v-0fc8da48",
    path: "/blog/Java/Java-Collection.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fc8da48").then(next)
    },
  },
  {
    name: "v-063440bc",
    path: "/blog/Java/Java-Common.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-063440bc").then(next)
    },
  },
  {
    name: "v-574bf09c",
    path: "/blog/Java/Interface.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-574bf09c").then(next)
    },
  },
  {
    name: "v-f41999c8",
    path: "/blog/Java/FastJson/Fastjson-Use.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f41999c8").then(next)
    },
  },
  {
    name: "v-175d2bbc",
    path: "/blog/Java/FastJson/Fastjson-SerializeFilter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-175d2bbc").then(next)
    },
  },
  {
    name: "v-2947893c",
    path: "/blog/Java/Swagger.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2947893c").then(next)
    },
  },
  {
    name: "v-cf3b107c",
    path: "/blog/Java/Java-Toolkit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cf3b107c").then(next)
    },
  },
  {
    name: "v-4e49d5fc",
    path: "/blog/Live-Stream/AR.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e49d5fc").then(next)
    },
  },
  {
    name: "v-2869547c",
    path: "/blog/Live-Stream/JavaCV.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2869547c").then(next)
    },
  },
  {
    name: "v-eaf132c8",
    path: "/blog/Java/Java-list.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eaf132c8").then(next)
    },
  },
  {
    name: "v-28d93450",
    path: "/blog/Live-Stream/WebSocket.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28d93450").then(next)
    },
  },
  {
    name: "v-3501a244",
    path: "/blog/Markdown/Markdown-Flowchart.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3501a244").then(next)
    },
  },
  {
    name: "v-dfff36c8",
    path: "/blog/OS/Mac.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dfff36c8").then(next)
    },
  },
  {
    name: "v-58da28b8",
    path: "/blog/Markdown/Markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58da28b8").then(next)
    },
  },
  {
    name: "v-ae2b6a88",
    path: "/blog/OS/Linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ae2b6a88").then(next)
    },
  },
  {
    name: "v-79a9ea48",
    path: "/blog/OS/Kylin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79a9ea48").then(next)
    },
  },
  {
    name: "v-ad67ce6c",
    path: "/blog/Web/CSS/CSS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ad67ce6c").then(next)
    },
  },
  {
    name: "v-0e780248",
    path: "/blog/OS/Virtual-Machine.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e780248").then(next)
    },
  },
  {
    name: "v-d38cf784",
    path: "/blog/Web/Vue/Vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d38cf784").then(next)
    },
  },
  {
    name: "v-17a98614",
    path: "/blog/Live-Stream/SRS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17a98614").then(next)
    },
  },
  {
    name: "v-175829bc",
    path: "/blog/Web/Vue/Vuepress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-175829bc").then(next)
    },
  },
  {
    name: "v-2a32d3bc",
    path: "/blog/Web/Android/Reference.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a32d3bc").then(next)
    },
  },
  {
    name: "v-7747d57c",
    path: "/blog/Web/JS/JS-Module-Specification.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7747d57c").then(next)
    },
  },
  {
    name: "v-da79eb82",
    path: "/blog/%E4%B8%B4%E6%97%B6%E5%AD%98%E5%82%A8/%E6%8A%93%E5%8C%85%E5%B7%A5%E5%85%B7%20Fiddler/Fiddler.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-da79eb82").then(next)
    },
  },
  {
    path: "/blog/临时存储/抓包工具 Fiddler/Fiddler.html",
    redirect: "/blog/%E4%B8%B4%E6%97%B6%E5%AD%98%E5%82%A8/%E6%8A%93%E5%8C%85%E5%B7%A5%E5%85%B7%20Fiddler/Fiddler.html"
  },
  {
    path: "/blog/临时存储/抓包工具 Fiddler/Fiddler.html",
    redirect: "/blog/%E4%B8%B4%E6%97%B6%E5%AD%98%E5%82%A8/%E6%8A%93%E5%8C%85%E5%B7%A5%E5%85%B7%20Fiddler/Fiddler.html"
  },
  {
    name: "v-bec16b48",
    path: "/blog/Web/IDE/VSCode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bec16b48").then(next)
    },
  },
  {
    name: "v-d038b8de",
    path: "/blog/%E6%A6%82%E5%BF%B5%E6%A2%B3%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d038b8de").then(next)
    },
  },
  {
    path: "/blog/概念梳理.html",
    redirect: "/blog/%E6%A6%82%E5%BF%B5%E6%A2%B3%E7%90%86.html"
  },
  {
    path: "/blog/概念梳理.html",
    redirect: "/blog/%E6%A6%82%E5%BF%B5%E6%A2%B3%E7%90%86.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]