/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "熊猫🐼",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "logo.jpeg"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.jpeg",
        "heroText": "熊猫🐼",
        "tagline": "文档集中存储",
        "actionText": "前往工具包 →",
        "actionLink": "/blog/Tool/Menu.md",
        "footer": "MIT Licensed | Copyright © 2021-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-8afcb3ee",
      "path": "/"
    },
    {
      "title": "架构梳理",
      "frontmatter": {},
      "regularPath": "/blog/20210726-%E6%9E%B6%E6%9E%84%E6%A2%B3%E7%90%86.html",
      "relativePath": "blog/20210726-架构梳理.md",
      "key": "v-710628bd",
      "path": "/blog/20210726-%E6%9E%B6%E6%9E%84%E6%A2%B3%E7%90%86.html",
      "headers": [
        {
          "level": 2,
          "title": "主框架",
          "slug": "主框架"
        },
        {
          "level": 2,
          "title": "组件",
          "slug": "组件"
        }
      ]
    },
    {
      "title": "安装Mongodb",
      "frontmatter": {},
      "regularPath": "/blog/Database/MongoDB/MongoDB-Init.html",
      "relativePath": "blog/Database/MongoDB/MongoDB-Init.md",
      "key": "v-1c4ddd40",
      "path": "/blog/Database/MongoDB/MongoDB-Init.html",
      "headers": [
        {
          "level": 2,
          "title": "MAC OSX平台安装MongdoDB",
          "slug": "mac-osx平台安装mongdodb"
        },
        {
          "level": 3,
          "title": "下载安装",
          "slug": "下载安装"
        },
        {
          "level": 3,
          "title": "启动/配置",
          "slug": "启动-配置"
        },
        {
          "level": 3,
          "title": "关闭服务",
          "slug": "关闭服务"
        },
        {
          "level": 2,
          "title": "使用 brew 安装",
          "slug": "使用-brew-安装"
        }
      ]
    },
    {
      "title": "MongoDB",
      "frontmatter": {},
      "regularPath": "/blog/Database/MongoDB/Menu.html",
      "relativePath": "blog/Database/MongoDB/Menu.md",
      "key": "v-0cc39ed8",
      "path": "/blog/Database/MongoDB/Menu.html"
    },
    {
      "title": "MongoDB 执行JS脚本",
      "frontmatter": {},
      "regularPath": "/blog/Database/MongoDB/MongoDB-JS.html",
      "relativePath": "blog/Database/MongoDB/MongoDB-JS.md",
      "key": "v-69eaba8e",
      "path": "/blog/Database/MongoDB/MongoDB-JS.html",
      "headers": [
        {
          "level": 2,
          "title": "脚本执行方法",
          "slug": "脚本执行方法"
        },
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 3,
          "title": "数据库连接相关语法",
          "slug": "数据库连接相关语法"
        },
        {
          "level": 3,
          "title": "日志打印语法",
          "slug": "日志打印语法"
        }
      ]
    },
    {
      "title": "MongoDB Shell 文档",
      "frontmatter": {},
      "regularPath": "/blog/Database/MongoDB/MongoDB-Shell-Detail.html",
      "relativePath": "blog/Database/MongoDB/MongoDB-Shell-Detail.md",
      "key": "v-6fa795f8",
      "path": "/blog/Database/MongoDB/MongoDB-Shell-Detail.html",
      "headers": [
        {
          "level": 2,
          "title": "查询 find()",
          "slug": "查询-find"
        },
        {
          "level": 3,
          "title": "查询函数",
          "slug": "查询函数"
        },
        {
          "level": 3,
          "title": "查询操作符",
          "slug": "查询操作符"
        },
        {
          "level": 3,
          "title": "特殊查询",
          "slug": "特殊查询"
        },
        {
          "level": 2,
          "title": "聚合查询 aggregate()",
          "slug": "聚合查询-aggregate"
        },
        {
          "level": 3,
          "title": "管道的概念",
          "slug": "管道的概念"
        },
        {
          "level": 3,
          "title": "$project",
          "slug": "project"
        },
        {
          "level": 3,
          "title": "$group",
          "slug": "group"
        },
        {
          "level": 2,
          "title": "新增",
          "slug": "新增"
        },
        {
          "level": 3,
          "title": "新增函数",
          "slug": "新增函数"
        },
        {
          "level": 2,
          "title": "修改",
          "slug": "修改"
        },
        {
          "level": 3,
          "title": "修改函数",
          "slug": "修改函数"
        },
        {
          "level": 3,
          "title": "修改操作符",
          "slug": "修改操作符"
        },
        {
          "level": 2,
          "title": "删除",
          "slug": "删除"
        },
        {
          "level": 3,
          "title": "普通删除",
          "slug": "普通删除"
        }
      ]
    },
    {
      "title": "MongoDB shell语法",
      "frontmatter": {},
      "regularPath": "/blog/Database/MongoDB/MongoDB-Shell.html",
      "relativePath": "blog/Database/MongoDB/MongoDB-Shell.md",
      "key": "v-143c8852",
      "path": "/blog/Database/MongoDB/MongoDB-Shell.html",
      "headers": [
        {
          "level": 2,
          "title": "命令行选项",
          "slug": "命令行选项"
        },
        {
          "level": 2,
          "title": "命令助手",
          "slug": "命令助手"
        },
        {
          "level": 2,
          "title": "Shell JavaScript基本操作",
          "slug": "shell-javascript基本操作"
        },
        {
          "level": 2,
          "title": "查询",
          "slug": "查询"
        },
        {
          "level": 2,
          "title": "错误检查方法",
          "slug": "错误检查方法"
        },
        {
          "level": 2,
          "title": "管理命令助手",
          "slug": "管理命令助手"
        },
        {
          "level": 2,
          "title": "打开附加连接",
          "slug": "打开附加连接"
        },
        {
          "level": 2,
          "title": "杂项",
          "slug": "杂项"
        },
        {
          "level": 2,
          "title": "其他资源",
          "slug": "其他资源"
        }
      ]
    },
    {
      "title": "MongoDB",
      "frontmatter": {},
      "regularPath": "/blog/Database/MongoDB/MongoDB-Wait.html",
      "relativePath": "blog/Database/MongoDB/MongoDB-Wait.md",
      "key": "v-198ee314",
      "path": "/blog/Database/MongoDB/MongoDB-Wait.html",
      "headers": [
        {
          "level": 2,
          "title": "MongoDB只查询一个字段",
          "slug": "mongodb只查询一个字段"
        },
        {
          "level": 2,
          "title": "根据id查询",
          "slug": "根据id查询"
        },
        {
          "level": 2,
          "title": "ObjectId类型转换成string",
          "slug": "objectid类型转换成string"
        }
      ]
    },
    {
      "title": "Mysql",
      "frontmatter": {},
      "regularPath": "/blog/Database/Mysql/Menu.html",
      "relativePath": "blog/Database/Mysql/Menu.md",
      "key": "v-52048810",
      "path": "/blog/Database/Mysql/Menu.html"
    },
    {
      "title": "Mysql 常见的错误",
      "frontmatter": {},
      "regularPath": "/blog/Database/Mysql/Mysql-Error.html",
      "relativePath": "blog/Database/Mysql/Mysql-Error.md",
      "key": "v-7b1be05c",
      "path": "/blog/Database/Mysql/Mysql-Error.html",
      "headers": [
        {
          "level": 2,
          "title": "Error Code: 1175. You are using safe update",
          "slug": "error-code-1175-you-are-using-safe-update"
        },
        {
          "level": 2,
          "title": "mysql解决只能用localhost连接,不能用ip连接的问题",
          "slug": "mysql解决只能用localhost连接-不能用ip连接的问题"
        }
      ]
    },
    {
      "title": "安装Mysql",
      "frontmatter": {},
      "regularPath": "/blog/Database/Mysql/Mysql-Init.html",
      "relativePath": "blog/Database/Mysql/Mysql-Init.md",
      "key": "v-0396cb00",
      "path": "/blog/Database/Mysql/Mysql-Init.html",
      "headers": [
        {
          "level": 2,
          "title": "Mac OSX 安装Mysql",
          "slug": "mac-osx-安装mysql"
        }
      ]
    },
    {
      "title": "Mysql Shell使用说明",
      "frontmatter": {},
      "regularPath": "/blog/Database/Mysql/Mysql-Shell.html",
      "relativePath": "blog/Database/Mysql/Mysql-Shell.md",
      "key": "v-35b620d2",
      "path": "/blog/Database/Mysql/Mysql-Shell.html",
      "headers": [
        {
          "level": 2,
          "title": "进入控制台",
          "slug": "进入控制台"
        },
        {
          "level": 2,
          "title": "提示符信息",
          "slug": "提示符信息"
        },
        {
          "level": 2,
          "title": "客户端帮助",
          "slug": "客户端帮助"
        }
      ]
    },
    {
      "title": "达梦数据库",
      "frontmatter": {},
      "regularPath": "/blog/Database/Other/DM.html",
      "relativePath": "blog/Database/Other/DM.md",
      "key": "v-29dab880",
      "path": "/blog/Database/Other/DM.html",
      "headers": [
        {
          "level": 3,
          "title": "mysql数据库转达梦数据库方法",
          "slug": "mysql数据库转达梦数据库方法"
        },
        {
          "level": 3,
          "title": "达梦数据库 无效的表或试图名问题",
          "slug": "达梦数据库-无效的表或试图名问题"
        },
        {
          "level": 3,
          "title": "达梦数据库SQL指南",
          "slug": "达梦数据库sql指南"
        },
        {
          "level": 3,
          "title": "达梦数据库常用sql语句",
          "slug": "达梦数据库常用sql语句"
        }
      ]
    },
    {
      "title": "其他数据库",
      "frontmatter": {},
      "regularPath": "/blog/Database/Other/Menu.html",
      "relativePath": "blog/Database/Other/Menu.md",
      "key": "v-3e0c44d4",
      "path": "/blog/Database/Other/Menu.html",
      "headers": [
        {
          "level": 2,
          "title": "其他数据库",
          "slug": "其他数据库"
        }
      ]
    },
    {
      "title": "Redis",
      "frontmatter": {},
      "regularPath": "/blog/Database/Redis/Menu.html",
      "relativePath": "blog/Database/Redis/Menu.md",
      "key": "v-3d0d1faa",
      "path": "/blog/Database/Redis/Menu.html"
    },
    {
      "title": "Redis 安装/服务暂停与启动",
      "frontmatter": {},
      "regularPath": "/blog/Database/Redis/Redis-Init.html",
      "relativePath": "blog/Database/Redis/Redis-Init.md",
      "key": "v-12792764",
      "path": "/blog/Database/Redis/Redis-Init.html",
      "headers": [
        {
          "level": 2,
          "title": "Mac 系统",
          "slug": "mac-系统"
        },
        {
          "level": 3,
          "title": "安装Homebrew",
          "slug": "安装homebrew"
        },
        {
          "level": 3,
          "title": "使用Homebrew安装Redis",
          "slug": "使用homebrew安装redis"
        },
        {
          "level": 2,
          "title": "Linux 系统",
          "slug": "linux-系统"
        },
        {
          "level": 3,
          "title": "Linux安装Redis",
          "slug": "linux安装redis"
        }
      ]
    },
    {
      "title": "抽象类(abstract)",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Abstract-Interface/Abstract.html",
      "relativePath": "blog/Java/Common/Abstract-Interface/Abstract.md",
      "key": "v-0823d4c0",
      "path": "/blog/Java/Common/Abstract-Interface/Abstract.html"
    },
    {
      "title": "接口(interface)",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Abstract-Interface/Interface.html",
      "relativePath": "blog/Java/Common/Abstract-Interface/Interface.md",
      "key": "v-00b1c1b2",
      "path": "/blog/Java/Common/Abstract-Interface/Interface.html"
    },
    {
      "title": "抽象类/接口",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Abstract-Interface/Menu.html",
      "relativePath": "blog/Java/Common/Abstract-Interface/Menu.md",
      "key": "v-67b27734",
      "path": "/blog/Java/Common/Abstract-Interface/Menu.html"
    },
    {
      "title": "HashMap",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Collection/Map/HashMap.html",
      "relativePath": "blog/Java/Common/Collection/Map/HashMap.md",
      "key": "v-515163f2",
      "path": "/blog/Java/Common/Collection/Map/HashMap.html",
      "headers": [
        {
          "level": 2,
          "title": "初始化",
          "slug": "初始化"
        },
        {
          "level": 2,
          "title": "扩容 resize()",
          "slug": "扩容-resize"
        }
      ]
    },
    {
      "title": "Java 集合",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Collection/Menu.html",
      "relativePath": "blog/Java/Common/Collection/Menu.md",
      "key": "v-2dc75746",
      "path": "/blog/Java/Common/Collection/Menu.html",
      "headers": [
        {
          "level": 2,
          "title": "Java 集合",
          "slug": "java-集合"
        }
      ]
    },
    {
      "title": "排序",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Collection/sort.html",
      "relativePath": "blog/Java/Common/Collection/sort.md",
      "key": "v-2f592948",
      "path": "/blog/Java/Common/Collection/sort.html",
      "headers": [
        {
          "level": 2,
          "title": "Java 8 Comparator: 列表排序",
          "slug": "java-8-comparator-列表排序"
        },
        {
          "level": 3,
          "title": "1.按字母顺序排序字符串列表",
          "slug": "_1-按字母顺序排序字符串列表"
        },
        {
          "level": 3,
          "title": "2.对整数列表进行排序",
          "slug": "_2-对整数列表进行排序"
        },
        {
          "level": 3,
          "title": "3.按字符串字段对列表进行排序",
          "slug": "_3-按字符串字段对列表进行排序"
        },
        {
          "level": 3,
          "title": "4.按Double字段排序列表",
          "slug": "_4-按double字段排序列表"
        },
        {
          "level": 3,
          "title": "5.使用自定义比较器对列表进行排序",
          "slug": "_5-使用自定义比较器对列表进行排序"
        },
        {
          "level": 3,
          "title": "6.使用比较器链对列表进行排序",
          "slug": "_6-使用比较器链对列表进行排序"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Abstract-Factory-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Abstract-Factory-Mode.md",
      "key": "v-1028113e",
      "path": "/blog/Java/Common/Design-Patterns/Abstract-Factory-Mode.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Adapter-Pattern.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Adapter-Pattern.md",
      "key": "v-72e5fe88",
      "path": "/blog/Java/Common/Design-Patterns/Adapter-Pattern.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Agency-Model.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Agency-Model.md",
      "key": "v-d9bb7e1c",
      "path": "/blog/Java/Common/Design-Patterns/Agency-Model.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Appearance-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Appearance-Mode.md",
      "key": "v-6557ed08",
      "path": "/blog/Java/Common/Design-Patterns/Appearance-Mode.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Bridge-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Bridge-Mode.md",
      "key": "v-4cc6c652",
      "path": "/blog/Java/Common/Design-Patterns/Bridge-Mode.html"
    },
    {
      "title": "建造者模式",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Builder-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Builder-Mode.md",
      "key": "v-5b106a72",
      "path": "/blog/Java/Common/Design-Patterns/Builder-Mode.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "一、简介",
          "slug": "一、简介"
        },
        {
          "level": 2,
          "title": "二、实现方式",
          "slug": "二、实现方式"
        },
        {
          "level": 2,
          "title": "三、常见第一种方式",
          "slug": "三、常见第一种方式"
        },
        {
          "level": 3,
          "title": "（1）一般有以下几个角色",
          "slug": "_1-一般有以下几个角色"
        },
        {
          "level": 3,
          "title": "（2）举个例子",
          "slug": "_2-举个例子"
        },
        {
          "level": 3,
          "title": "（3）具体步骤",
          "slug": "_3-具体步骤"
        },
        {
          "level": 3,
          "title": "（4）具体代码",
          "slug": "_4-具体代码"
        },
        {
          "level": 2,
          "title": "三、第二种方式",
          "slug": "三、第二种方式"
        },
        {
          "level": 3,
          "title": "（1）主要有三个角色：抽象建造者、具体建造者、产品",
          "slug": "_1-主要有三个角色-抽象建造者、具体建造者、产品"
        },
        {
          "level": 3,
          "title": "（2）举个例子",
          "slug": "_2-举个例子-2"
        },
        {
          "level": 3,
          "title": "（3）具体步骤",
          "slug": "_3-具体步骤-2"
        },
        {
          "level": 3,
          "title": "（4）具体代码",
          "slug": "_4-具体代码-2"
        },
        {
          "level": 2,
          "title": "四、总结",
          "slug": "四、总结"
        },
        {
          "level": 3,
          "title": "（1）优点",
          "slug": "_1-优点"
        },
        {
          "level": 3,
          "title": "（2）缺点",
          "slug": "_2-缺点"
        },
        {
          "level": 3,
          "title": "（3）应用场景",
          "slug": "_3-应用场景"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Chain-Of-Responsibility-Model.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Chain-Of-Responsibility-Model.md",
      "key": "v-73f95d10",
      "path": "/blog/Java/Common/Design-Patterns/Chain-Of-Responsibility-Model.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Combination-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Combination-Mode.md",
      "key": "v-07be53f2",
      "path": "/blog/Java/Common/Design-Patterns/Combination-Mode.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Command-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Command-Mode.md",
      "key": "v-02c70072",
      "path": "/blog/Java/Common/Design-Patterns/Command-Mode.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Decorator-Pattern.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Decorator-Pattern.md",
      "key": "v-2c652cb8",
      "path": "/blog/Java/Common/Design-Patterns/Decorator-Pattern.html"
    },
    {
      "title": "工厂模式",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Factory-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Factory-Mode.md",
      "key": "v-36758b5c",
      "path": "/blog/Java/Common/Design-Patterns/Factory-Mode.html",
      "headers": [
        {
          "level": 2,
          "title": "一、简介",
          "slug": "一、简介"
        },
        {
          "level": 2,
          "title": "二、简单工厂模式",
          "slug": "二、简单工厂模式"
        },
        {
          "level": 2,
          "title": "三、工厂方法模式",
          "slug": "三、工厂方法模式"
        },
        {
          "level": 2,
          "title": "四、抽象工厂模式",
          "slug": "四、抽象工厂模式"
        },
        {
          "level": 2,
          "title": "五、总结",
          "slug": "五、总结"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Flyweight-Model.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Flyweight-Model.md",
      "key": "v-897a2adc",
      "path": "/blog/Java/Common/Design-Patterns/Flyweight-Model.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Intermediary-Model.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Intermediary-Model.md",
      "key": "v-8c05769c",
      "path": "/blog/Java/Common/Design-Patterns/Intermediary-Model.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Interpreter-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Interpreter-Mode.md",
      "key": "v-2a839e5c",
      "path": "/blog/Java/Common/Design-Patterns/Interpreter-Mode.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Iterative-Subpattern.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Iterative-Subpattern.md",
      "key": "v-5e7a8012",
      "path": "/blog/Java/Common/Design-Patterns/Iterative-Subpattern.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Memo-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Memo-Mode.md",
      "key": "v-68eec574",
      "path": "/blog/Java/Common/Design-Patterns/Memo-Mode.html"
    },
    {
      "title": "java23种设计模式",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Menu.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Menu.md",
      "key": "v-d85a6d9c",
      "path": "/blog/Java/Common/Design-Patterns/Menu.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Observer-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Observer-Mode.md",
      "key": "v-578939a8",
      "path": "/blog/Java/Common/Design-Patterns/Observer-Mode.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Prototype-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Prototype-Mode.md",
      "key": "v-1f7e7392",
      "path": "/blog/Java/Common/Design-Patterns/Prototype-Mode.html"
    },
    {
      "title": "单例模式",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Singleton-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Singleton-Mode.md",
      "key": "v-f809061c",
      "path": "/blog/Java/Common/Design-Patterns/Singleton-Mode.html",
      "headers": [
        {
          "level": 2,
          "title": "概念",
          "slug": "概念"
        },
        {
          "level": 2,
          "title": "饿汉式",
          "slug": "饿汉式"
        },
        {
          "level": 3,
          "title": "静态常量方式",
          "slug": "静态常量方式"
        },
        {
          "level": 3,
          "title": "静态代码块方式",
          "slug": "静态代码块方式"
        },
        {
          "level": 3,
          "title": "枚举形式",
          "slug": "枚举形式"
        },
        {
          "level": 2,
          "title": "懒汉式",
          "slug": "懒汉式"
        },
        {
          "level": 3,
          "title": "双重检查",
          "slug": "双重检查"
        },
        {
          "level": 3,
          "title": "静态内部类形式",
          "slug": "静态内部类形式"
        },
        {
          "level": 2,
          "title": "使用场景",
          "slug": "使用场景"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/State-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/State-Mode.md",
      "key": "v-78d2819c",
      "path": "/blog/Java/Common/Design-Patterns/State-Mode.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Strategy-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Strategy-Mode.md",
      "key": "v-a395dab4",
      "path": "/blog/Java/Common/Design-Patterns/Strategy-Mode.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Template-Method-Pattern.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Template-Method-Pattern.md",
      "key": "v-4e162cb2",
      "path": "/blog/Java/Common/Design-Patterns/Template-Method-Pattern.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Design-Patterns/Visitor-Mode.html",
      "relativePath": "blog/Java/Common/Design-Patterns/Visitor-Mode.md",
      "key": "v-6ff0ded2",
      "path": "/blog/Java/Common/Design-Patterns/Visitor-Mode.html"
    },
    {
      "title": "IO",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/IO/Menu.html",
      "relativePath": "blog/Java/Common/IO/Menu.md",
      "key": "v-b0fdd7d4",
      "path": "/blog/Java/Common/IO/Menu.html"
    },
    {
      "title": "文件处理",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/IO/file.html",
      "relativePath": "blog/Java/Common/IO/file.md",
      "key": "v-594d65dc",
      "path": "/blog/Java/Common/IO/file.html",
      "headers": [
        {
          "level": 2,
          "title": "读取txt文件",
          "slug": "读取txt文件"
        },
        {
          "level": 3,
          "title": "读取全部文件",
          "slug": "读取全部文件"
        },
        {
          "level": 2,
          "title": "图片处理（javax.imageio.ImageIO）",
          "slug": "图片处理-javax-imageio-imageio"
        },
        {
          "level": 3,
          "title": "检测当前文件是不是图片",
          "slug": "检测当前文件是不是图片"
        }
      ]
    },
    {
      "title": "fastjson - 自定义反序列化",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/JSON/FastJson/Fastjson-Deserialize.html",
      "relativePath": "blog/Java/Common/JSON/FastJson/Fastjson-Deserialize.md",
      "key": "v-2b8554f2",
      "path": "/blog/Java/Common/JSON/FastJson/Fastjson-Deserialize.html",
      "headers": [
        {
          "level": 2,
          "title": "场景",
          "slug": "场景"
        },
        {
          "level": 2,
          "title": "自定义反序列化解析器 - ObjectDeserializer",
          "slug": "自定义反序列化解析器-objectdeserializer"
        },
        {
          "level": 2,
          "title": "使用解析器",
          "slug": "使用解析器"
        }
      ]
    },
    {
      "title": "JSONField与JSONType注解的使用",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/JSON/FastJson/Fastjson-JSONField-JSONType.html",
      "relativePath": "blog/Java/Common/JSON/FastJson/Fastjson-JSONField-JSONType.md",
      "key": "v-1521febc",
      "path": "/blog/Java/Common/JSON/FastJson/Fastjson-JSONField-JSONType.html",
      "headers": [
        {
          "level": 2,
          "title": "@JSONField",
          "slug": "jsonfield"
        },
        {
          "level": 2,
          "title": "@JSONType",
          "slug": "jsontype"
        }
      ]
    },
    {
      "title": "fastjson - 自定义序列化",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/JSON/FastJson/Fastjson-Serialize.html",
      "relativePath": "blog/Java/Common/JSON/FastJson/Fastjson-Serialize.md",
      "key": "v-c991505c",
      "path": "/blog/Java/Common/JSON/FastJson/Fastjson-Serialize.html",
      "headers": [
        {
          "level": 2,
          "title": "场景",
          "slug": "场景"
        },
        {
          "level": 2,
          "title": "自定义反序列化解析器 - ObjectSerializer",
          "slug": "自定义反序列化解析器-objectserializer"
        },
        {
          "level": 2,
          "title": "使用解析器",
          "slug": "使用解析器"
        },
        {
          "level": 2,
          "title": "序列化相关的概念",
          "slug": "序列化相关的概念"
        }
      ]
    },
    {
      "title": "SerializeFilter",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/JSON/FastJson/Fastjson-SerializeFilter.html",
      "relativePath": "blog/Java/Common/JSON/FastJson/Fastjson-SerializeFilter.md",
      "key": "v-5a21ed92",
      "path": "/blog/Java/Common/JSON/FastJson/Fastjson-SerializeFilter.html"
    },
    {
      "title": "Fastjson - SerializerFeature特性的使用",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/JSON/FastJson/Fastjson-SerializerFeature.html",
      "relativePath": "blog/Java/Common/JSON/FastJson/Fastjson-SerializerFeature.md",
      "key": "v-0cda9e52",
      "path": "/blog/Java/Common/JSON/FastJson/Fastjson-SerializerFeature.html"
    },
    {
      "title": "Fastjson 使用",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/JSON/FastJson/Fastjson-Use.html",
      "relativePath": "blog/Java/Common/JSON/FastJson/Fastjson-Use.md",
      "key": "v-23c88bf2",
      "path": "/blog/Java/Common/JSON/FastJson/Fastjson-Use.html"
    },
    {
      "title": "JSON",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/JSON/Menu.html",
      "relativePath": "blog/Java/Common/JSON/Menu.md",
      "key": "v-f39cbdcc",
      "path": "/blog/Java/Common/JSON/Menu.html"
    },
    {
      "title": "Java基础（https://zhuanlan.zhihu.com/p/28615617）",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Menu.html",
      "relativePath": "blog/Java/Common/Menu.md",
      "key": "v-001817d2",
      "path": "/blog/Java/Common/Menu.html"
    },
    {
      "title": "idea",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/IDE/IDEA-Wait.html",
      "relativePath": "blog/Java/Java-Frame/IDE/IDEA-Wait.md",
      "key": "v-0a754b6c",
      "path": "/blog/Java/Java-Frame/IDE/IDEA-Wait.html",
      "headers": [
        {
          "level": 2,
          "title": "常用操作",
          "slug": "常用操作"
        },
        {
          "level": 2,
          "title": "常见问题",
          "slug": "常见问题"
        },
        {
          "level": 2,
          "title": "常用快捷键",
          "slug": "常用快捷键"
        },
        {
          "level": 3,
          "title": "Idea mac 自动补全函数返回值快捷键",
          "slug": "idea-mac-自动补全函数返回值快捷键"
        },
        {
          "level": 3,
          "title": "idea格式化代码快捷键",
          "slug": "idea格式化代码快捷键"
        }
      ]
    },
    {
      "title": "IDEA 使用说明",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/IDE/IDEA.html",
      "relativePath": "blog/Java/Java-Frame/IDE/IDEA.md",
      "key": "v-904cb7dc",
      "path": "/blog/Java/Java-Frame/IDE/IDEA.html",
      "headers": [
        {
          "level": 2,
          "title": "如何将Spring Boot打成war包",
          "slug": "如何将spring-boot打成war包"
        }
      ]
    },
    {
      "title": "logback",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Log/Logback.html",
      "relativePath": "blog/Java/Java-Frame/Log/Logback.md",
      "key": "v-59a748b8",
      "path": "/blog/Java/Java-Frame/Log/Logback.html",
      "headers": [
        {
          "level": 2,
          "title": "application.properties",
          "slug": "application-properties"
        },
        {
          "level": 3,
          "title": "logback.xml",
          "slug": "logback-xml"
        }
      ]
    },
    {
      "title": "Maven pom文件详解",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Maven/Maven-Pom.html",
      "relativePath": "blog/Java/Java-Frame/Maven/Maven-Pom.md",
      "key": "v-633e4b28",
      "path": "/blog/Java/Java-Frame/Maven/Maven-Pom.html",
      "headers": [
        {
          "level": 2,
          "title": "简单介绍",
          "slug": "简单介绍"
        },
        {
          "level": 2,
          "title": "详细描述",
          "slug": "详细描述"
        },
        {
          "level": 3,
          "title": "dependencyManagement节点",
          "slug": "dependencymanagement节点"
        }
      ]
    },
    {
      "title": "Apollo",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Other/apollo.html",
      "relativePath": "blog/Java/Java-Frame/Other/apollo.md",
      "key": "v-2fc5c75c",
      "path": "/blog/Java/Java-Frame/Other/apollo.html",
      "headers": [
        {
          "level": 2,
          "title": "入门",
          "slug": "入门"
        }
      ]
    },
    {
      "title": "Java 框架级",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Menu.html",
      "relativePath": "blog/Java/Java-Frame/Menu.md",
      "key": "v-10fdac9c",
      "path": "/blog/Java/Java-Frame/Menu.html",
      "headers": [
        {
          "level": 2,
          "title": "Spring",
          "slug": "spring"
        },
        {
          "level": 2,
          "title": "SpringBoot",
          "slug": "springboot"
        },
        {
          "level": 2,
          "title": "SpringCloud",
          "slug": "springcloud"
        },
        {
          "level": 2,
          "title": "Tomcat",
          "slug": "tomcat"
        },
        {
          "level": 2,
          "title": "Quartz",
          "slug": "quartz"
        },
        {
          "level": 2,
          "title": "Maven",
          "slug": "maven"
        },
        {
          "level": 2,
          "title": "Log框架",
          "slug": "log框架"
        },
        {
          "level": 2,
          "title": "IDE",
          "slug": "ide"
        },
        {
          "level": 2,
          "title": "其他",
          "slug": "其他"
        }
      ]
    },
    {
      "title": "kafka 往这一堆",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Other/kafka.html",
      "relativePath": "blog/Java/Java-Frame/Other/kafka.md",
      "key": "v-cb9f12ac",
      "path": "/blog/Java/Java-Frame/Other/kafka.html",
      "headers": [
        {
          "level": 2,
          "title": "多场景配置。",
          "slug": "多场景配置。"
        }
      ]
    },
    {
      "title": "MQ",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Other/mq.html",
      "relativePath": "blog/Java/Java-Frame/Other/mq.md",
      "key": "v-8348c99c",
      "path": "/blog/Java/Java-Frame/Other/mq.html",
      "headers": [
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 3,
          "title": "启动：(暂时)",
          "slug": "启动-暂时"
        },
        {
          "level": 2,
          "title": "安装配置",
          "slug": "安装配置"
        },
        {
          "level": 2,
          "title": "常见错误",
          "slug": "常见错误"
        }
      ]
    },
    {
      "title": "Nacos",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Other/nacos.html",
      "relativePath": "blog/Java/Java-Frame/Other/nacos.md",
      "key": "v-2f7e4f8e",
      "path": "/blog/Java/Java-Frame/Other/nacos.html",
      "headers": [
        {
          "level": 2,
          "title": "入门",
          "slug": "入门"
        }
      ]
    },
    {
      "title": "Nginx",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Other/nginx.html",
      "relativePath": "blog/Java/Java-Frame/Other/nginx.md",
      "key": "v-5d0998c2",
      "path": "/blog/Java/Java-Frame/Other/nginx.html",
      "headers": [
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "思路",
          "slug": "思路"
        },
        {
          "level": 3,
          "title": "修改 nginx 的默认端口",
          "slug": "修改-nginx-的默认端口"
        }
      ]
    },
    {
      "title": "Spring Boot整合Quartz持久化到数据库",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Quartz/Quartz-Database.html",
      "relativePath": "blog/Java/Java-Frame/Quartz/Quartz-Database.md",
      "key": "v-0d36281c",
      "path": "/blog/Java/Java-Frame/Quartz/Quartz-Database.html",
      "headers": [
        {
          "level": 2,
          "title": "maven依赖",
          "slug": "maven依赖"
        },
        {
          "level": 2,
          "title": "Mysql sql文件",
          "slug": "mysql-sql文件"
        },
        {
          "level": 2,
          "title": "项目信息配置（quartz.properties）",
          "slug": "项目信息配置-quartz-properties"
        },
        {
          "level": 2,
          "title": "Job服务统一执行类（JobAutoExe）",
          "slug": "job服务统一执行类-jobautoexe"
        },
        {
          "level": 2,
          "title": "项目配置（QuartzConfig）",
          "slug": "项目配置-quartzconfig"
        },
        {
          "level": 2,
          "title": "Job服务调用（QuartzService）",
          "slug": "job服务调用-quartzservice"
        },
        {
          "level": 2,
          "title": "Job实体类（JobDataMap）",
          "slug": "job实体类-jobdatamap"
        },
        {
          "level": 2,
          "title": "Job服务调用（JobController）",
          "slug": "job服务调用-jobcontroller"
        },
        {
          "level": 2,
          "title": "测试Job（TestJob）",
          "slug": "测试job-testjob"
        }
      ]
    },
    {
      "title": "Quartz 提升",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Quartz/Quartz-Up.html",
      "relativePath": "blog/Java/Java-Frame/Quartz/Quartz-Up.md",
      "key": "v-ce200b1c",
      "path": "/blog/Java/Java-Frame/Quartz/Quartz-Up.html",
      "headers": [
        {
          "level": 2,
          "title": "并发控制（DisallowConcurrentExecution注解）",
          "slug": "并发控制-disallowconcurrentexecution注解"
        }
      ]
    },
    {
      "title": "spring event",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Spring/Spring-Event.html",
      "relativePath": "blog/Java/Java-Frame/Spring/Spring-Event.md",
      "key": "v-70902800",
      "path": "/blog/Java/Java-Frame/Spring/Spring-Event.html",
      "headers": [
        {
          "level": 2,
          "title": "spring event",
          "slug": "spring-event"
        },
        {
          "level": 3,
          "title": "1. 自定义Event",
          "slug": "_1-自定义event"
        },
        {
          "level": 3,
          "title": "2. 监听器",
          "slug": "_2-监听器"
        },
        {
          "level": 3,
          "title": "3. 消息发布者",
          "slug": "_3-消息发布者"
        },
        {
          "level": 3,
          "title": "4. 测试方法",
          "slug": "_4-测试方法"
        },
        {
          "level": 3,
          "title": "5. 结果",
          "slug": "_5-结果"
        },
        {
          "level": 3,
          "title": "6. 示例源码",
          "slug": "_6-示例源码"
        },
        {
          "level": 3,
          "title": "7. 扩展 - 监听事件时的事务隔离",
          "slug": "_7-扩展-监听事件时的事务隔离"
        }
      ]
    },
    {
      "title": "事务",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Spring/Spring-Transaction.html",
      "relativePath": "blog/Java/Java-Frame/Spring/Spring-Transaction.md",
      "key": "v-3e202538",
      "path": "/blog/Java/Java-Frame/Spring/Spring-Transaction.html",
      "headers": [
        {
          "level": 2,
          "title": "事务",
          "slug": "事务"
        },
        {
          "level": 3,
          "title": "事务操作（事务概念）",
          "slug": "事务操作-事务概念"
        },
        {
          "level": 3,
          "title": "事务操作（搭建事务操作环境）",
          "slug": "事务操作-搭建事务操作环境"
        },
        {
          "level": 3,
          "title": "事务操作（ Spring 事务管理介绍）",
          "slug": "事务操作-spring-事务管理介绍"
        },
        {
          "level": 3,
          "title": "事务操作（注解声明式事务管理）",
          "slug": "事务操作-注解声明式事务管理"
        },
        {
          "level": 3,
          "title": "事务操作（声明式事务管理参数配置）",
          "slug": "事务操作-声明式事务管理参数配置"
        },
        {
          "level": 3,
          "title": "事务操作（ XML 声明式事务管理）",
          "slug": "事务操作-xml-声明式事务管理"
        },
        {
          "level": 3,
          "title": "事务操作（完全注解声明式事务管理）",
          "slug": "事务操作-完全注解声明式事务管理"
        }
      ]
    },
    {
      "title": "Spring 参数校验器（Validator）",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Spring/Spring-Validator.html",
      "relativePath": "blog/Java/Java-Frame/Spring/Spring-Validator.md",
      "key": "v-48d8f1e0",
      "path": "/blog/Java/Java-Frame/Spring/Spring-Validator.html",
      "headers": [
        {
          "level": 2,
          "title": "用法实例",
          "slug": "用法实例"
        },
        {
          "level": 3,
          "title": "一、校验对象",
          "slug": "一、校验对象"
        },
        {
          "level": 3,
          "title": "二、直接校验参数",
          "slug": "二、直接校验参数"
        },
        {
          "level": 2,
          "title": "常见的校验注解",
          "slug": "常见的校验注解"
        },
        {
          "level": 2,
          "title": "自定义校验注解",
          "slug": "自定义校验注解"
        }
      ]
    },
    {
      "title": "SpringBoot 常用注解",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/SpringBoot/SpringBoot-Annotation.html",
      "relativePath": "blog/Java/Java-Frame/SpringBoot/SpringBoot-Annotation.md",
      "key": "v-c034801c",
      "path": "/blog/Java/Java-Frame/SpringBoot/SpringBoot-Annotation.html",
      "headers": [
        {
          "level": 2,
          "title": "启动类注解",
          "slug": "启动类注解"
        },
        {
          "level": 3,
          "title": "@SpringBootApplication",
          "slug": "springbootapplication"
        },
        {
          "level": 3,
          "title": "@EnableFeignClients",
          "slug": "enablefeignclients"
        },
        {
          "level": 3,
          "title": "@EnableEurekaClient",
          "slug": "enableeurekaclient"
        },
        {
          "level": 3,
          "title": "@MapperScan",
          "slug": "mapperscan"
        },
        {
          "level": 3,
          "title": "@EnableRedisHttpSession",
          "slug": "enableredishttpsession"
        }
      ]
    },
    {
      "title": "SpringBoot 项目搭建介绍",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/SpringBoot/SpringBoot-Init.html",
      "relativePath": "blog/Java/Java-Frame/SpringBoot/SpringBoot-Init.md",
      "key": "v-14869712",
      "path": "/blog/Java/Java-Frame/SpringBoot/SpringBoot-Init.html",
      "headers": [
        {
          "level": 2,
          "title": "父子项目搭建",
          "slug": "父子项目搭建"
        },
        {
          "level": 3,
          "title": "搭建流程",
          "slug": "搭建流程"
        },
        {
          "level": 3,
          "title": "描述",
          "slug": "描述"
        }
      ]
    },
    {
      "title": "SpringBoot 集成使用的组件",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/SpringBoot/SpringBoot-Tool.html",
      "relativePath": "blog/Java/Java-Frame/SpringBoot/SpringBoot-Tool.md",
      "key": "v-7ee4f412",
      "path": "/blog/Java/Java-Frame/SpringBoot/SpringBoot-Tool.html",
      "headers": [
        {
          "level": 2,
          "title": "jsoup(爬虫)",
          "slug": "jsoup-爬虫"
        },
        {
          "level": 3,
          "title": "maven",
          "slug": "maven"
        },
        {
          "level": 3,
          "title": "demo",
          "slug": "demo"
        },
        {
          "level": 2,
          "title": "Swagger API",
          "slug": "swagger-api"
        },
        {
          "level": 2,
          "title": "Hutool",
          "slug": "hutool"
        }
      ]
    },
    {
      "title": "Tomcat 安装/服务启动与关闭",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Tomcat/Tomcat-Init.html",
      "relativePath": "blog/Java/Java-Frame/Tomcat/Tomcat-Init.md",
      "key": "v-1d6323dc",
      "path": "/blog/Java/Java-Frame/Tomcat/Tomcat-Init.html",
      "headers": [
        {
          "level": 2,
          "title": "Linux ContOS7 安装 Tomcat9",
          "slug": "linux-contos7-安装-tomcat9"
        }
      ]
    },
    {
      "title": "Tomcat 启动web项目使用说明",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/Tomcat/Tomcat-run-web.html",
      "relativePath": "blog/Java/Java-Frame/Tomcat/Tomcat-run-web.md",
      "key": "v-6a0297d0",
      "path": "/blog/Java/Java-Frame/Tomcat/Tomcat-run-web.html",
      "headers": [
        {
          "level": 2,
          "title": "引入War包",
          "slug": "引入war包"
        }
      ]
    },
    {
      "title": "UP",
      "frontmatter": {},
      "regularPath": "/blog/Java/Tool/Menu.html",
      "relativePath": "blog/Java/Tool/Menu.md",
      "key": "v-42b4bbf2",
      "path": "/blog/Java/Tool/Menu.html"
    },
    {
      "title": "Awesome Java",
      "frontmatter": {},
      "regularPath": "/blog/Java/Tool/Awesome-Java.html",
      "relativePath": "blog/Java/Tool/Awesome-Java.md",
      "key": "v-d64cc8dc",
      "path": "/blog/Java/Tool/Awesome-Java.html",
      "headers": [
        {
          "level": 2,
          "title": "Build Tool",
          "slug": "build-tool"
        },
        {
          "level": 2,
          "title": "Bytecode Manipulation",
          "slug": "bytecode-manipulation"
        },
        {
          "level": 2,
          "title": "Cluster Management",
          "slug": "cluster-management"
        },
        {
          "level": 2,
          "title": "Code Analysis",
          "slug": "code-analysis"
        },
        {
          "level": 2,
          "title": "Compiler-compiler",
          "slug": "compiler-compiler"
        },
        {
          "level": 2,
          "title": "Configuration",
          "slug": "configuration"
        },
        {
          "level": 2,
          "title": "Constraint Satisfaction Problem Solver",
          "slug": "constraint-satisfaction-problem-solver"
        },
        {
          "level": 2,
          "title": "Continuous Integration",
          "slug": "continuous-integration"
        },
        {
          "level": 2,
          "title": "CSV",
          "slug": "csv"
        },
        {
          "level": 2,
          "title": "Database",
          "slug": "database"
        },
        {
          "level": 2,
          "title": "Data structures",
          "slug": "data-structures"
        },
        {
          "level": 2,
          "title": "Date and Time",
          "slug": "date-and-time"
        },
        {
          "level": 2,
          "title": "Dependency Injection",
          "slug": "dependency-injection"
        },
        {
          "level": 2,
          "title": "Development",
          "slug": "development"
        },
        {
          "level": 2,
          "title": "Distributed Applications",
          "slug": "distributed-applications"
        },
        {
          "level": 2,
          "title": "Distributed Databases",
          "slug": "distributed-databases"
        },
        {
          "level": 2,
          "title": "Distribution",
          "slug": "distribution"
        },
        {
          "level": 2,
          "title": "Document Processing",
          "slug": "document-processing"
        },
        {
          "level": 2,
          "title": "Functional Programming",
          "slug": "functional-programming"
        },
        {
          "level": 2,
          "title": "Game Development",
          "slug": "game-development"
        },
        {
          "level": 2,
          "title": "GUI",
          "slug": "gui"
        },
        {
          "level": 2,
          "title": "High Performance",
          "slug": "high-performance"
        },
        {
          "level": 2,
          "title": "IDE",
          "slug": "ide"
        },
        {
          "level": 2,
          "title": "Imagery",
          "slug": "imagery"
        },
        {
          "level": 2,
          "title": "JSON",
          "slug": "json"
        },
        {
          "level": 2,
          "title": "JVM and JDK",
          "slug": "jvm-and-jdk"
        },
        {
          "level": 2,
          "title": "Logging",
          "slug": "logging"
        },
        {
          "level": 2,
          "title": "Machine Learning",
          "slug": "machine-learning"
        },
        {
          "level": 2,
          "title": "Messaging",
          "slug": "messaging"
        },
        {
          "level": 2,
          "title": "Miscellaneous",
          "slug": "miscellaneous"
        },
        {
          "level": 2,
          "title": "Monitoring",
          "slug": "monitoring"
        },
        {
          "level": 2,
          "title": "Native",
          "slug": "native"
        },
        {
          "level": 2,
          "title": "Natural Language Processing",
          "slug": "natural-language-processing"
        },
        {
          "level": 2,
          "title": "Networking",
          "slug": "networking"
        },
        {
          "level": 2,
          "title": "ORM",
          "slug": "orm"
        },
        {
          "level": 2,
          "title": "PDF",
          "slug": "pdf"
        },
        {
          "level": 2,
          "title": "Performance analysis",
          "slug": "performance-analysis"
        },
        {
          "level": 2,
          "title": "REST Frameworks",
          "slug": "rest-frameworks"
        },
        {
          "level": 2,
          "title": "Science",
          "slug": "science"
        },
        {
          "level": 2,
          "title": "Search",
          "slug": "search"
        },
        {
          "level": 2,
          "title": "Security",
          "slug": "security"
        },
        {
          "level": 2,
          "title": "Serialization",
          "slug": "serialization"
        },
        {
          "level": 2,
          "title": "Server",
          "slug": "server"
        },
        {
          "level": 2,
          "title": "Template Engine",
          "slug": "template-engine"
        },
        {
          "level": 2,
          "title": "Testing",
          "slug": "testing"
        },
        {
          "level": 2,
          "title": "Utility",
          "slug": "utility"
        },
        {
          "level": 2,
          "title": "Web Crawling",
          "slug": "web-crawling"
        },
        {
          "level": 2,
          "title": "Web Frameworks",
          "slug": "web-frameworks"
        },
        {
          "level": 2,
          "title": "Communities",
          "slug": "communities"
        },
        {
          "level": 2,
          "title": "Influential Books",
          "slug": "influential-books"
        },
        {
          "level": 2,
          "title": "Podcasts",
          "slug": "podcasts"
        },
        {
          "level": 2,
          "title": "Twitter",
          "slug": "twitter"
        },
        {
          "level": 2,
          "title": "Websites",
          "slug": "websites"
        }
      ]
    },
    {
      "title": "接口开发",
      "frontmatter": {},
      "regularPath": "/blog/Java/wait/Annotation/Interface.html",
      "relativePath": "blog/Java/wait/Annotation/Interface.md",
      "key": "v-61659692",
      "path": "/blog/Java/wait/Annotation/Interface.html",
      "headers": [
        {
          "level": 2,
          "title": "注解",
          "slug": "注解"
        },
        {
          "level": 3,
          "title": "@RestController",
          "slug": "restcontroller"
        },
        {
          "level": 3,
          "title": "@PathVariable",
          "slug": "pathvariable"
        }
      ]
    },
    {
      "title": "package-info.java的使用",
      "frontmatter": {},
      "regularPath": "/blog/Java/wait/Annotation/package-info.html",
      "relativePath": "blog/Java/wait/Annotation/package-info.md",
      "key": "v-750b7f28",
      "path": "/blog/Java/wait/Annotation/package-info.html",
      "headers": [
        {
          "level": 2,
          "title": "场景",
          "slug": "场景"
        },
        {
          "level": 2,
          "title": "创建package-info.java",
          "slug": "创建package-info-java"
        },
        {
          "level": 2,
          "title": "package-info.java的使用",
          "slug": "package-info-java的使用-2"
        }
      ]
    },
    {
      "title": "docker 启动jar包",
      "frontmatter": {},
      "regularPath": "/blog/Operation-Maintenance/Docker/Docker-Jar.html",
      "relativePath": "blog/Operation-Maintenance/Docker/Docker-Jar.md",
      "key": "v-c55fbffc",
      "path": "/blog/Operation-Maintenance/Docker/Docker-Jar.html",
      "headers": [
        {
          "level": 2,
          "title": "编写dockerFile文件",
          "slug": "编写dockerfile文件"
        },
        {
          "level": 2,
          "title": "下载需要的外部包",
          "slug": "下载需要的外部包"
        },
        {
          "level": 2,
          "title": "执行dockerFile文件，构建镜像",
          "slug": "执行dockerfile文件-构建镜像"
        },
        {
          "level": 2,
          "title": "运行容器",
          "slug": "运行容器"
        }
      ]
    },
    {
      "title": "Docker shell命令",
      "frontmatter": {},
      "regularPath": "/blog/Operation-Maintenance/Docker/Docker-Shell.html",
      "relativePath": "blog/Operation-Maintenance/Docker/Docker-Shell.md",
      "key": "v-14d67158",
      "path": "/blog/Operation-Maintenance/Docker/Docker-Shell.html",
      "headers": [
        {
          "level": 2,
          "title": "基础命令",
          "slug": "基础命令"
        }
      ]
    },
    {
      "title": "Docker",
      "frontmatter": {},
      "regularPath": "/blog/Operation-Maintenance/Docker/Menu.html",
      "relativePath": "blog/Operation-Maintenance/Docker/Menu.md",
      "key": "v-2a434de0",
      "path": "/blog/Operation-Maintenance/Docker/Menu.html"
    },
    {
      "title": "银河麒麟",
      "frontmatter": {},
      "regularPath": "/blog/Operation-Maintenance/OS/Kylin.html",
      "relativePath": "blog/Operation-Maintenance/OS/Kylin.md",
      "key": "v-e0de35dc",
      "path": "/blog/Operation-Maintenance/OS/Kylin.html",
      "headers": [
        {
          "level": 3,
          "title": "银河麒麟安装达梦数据库",
          "slug": "银河麒麟安装达梦数据库"
        },
        {
          "level": 2,
          "title": "银河麒麟kylin使用root用户登录方法",
          "slug": "银河麒麟kylin使用root用户登录方法"
        },
        {
          "level": 3,
          "title": "银河麒麟4.0.2桌面版（arm平台）搭建Tomcat+Apache+nginx 环境",
          "slug": "银河麒麟4-0-2桌面版-arm平台-搭建tomcat-apache-nginx-环境"
        }
      ]
    },
    {
      "title": "Mac常见命令",
      "frontmatter": {},
      "regularPath": "/blog/Operation-Maintenance/OS/Mac.html",
      "relativePath": "blog/Operation-Maintenance/OS/Mac.md",
      "key": "v-d316dd5c",
      "path": "/blog/Operation-Maintenance/OS/Mac.html",
      "headers": [
        {
          "level": 2,
          "title": "Mac查看端口使用情况及停止端口使用",
          "slug": "mac查看端口使用情况及停止端口使用"
        },
        {
          "level": 2,
          "title": "Homebrew",
          "slug": "homebrew"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 3,
          "title": "使用国内镜像源",
          "slug": "使用国内镜像源"
        }
      ]
    },
    {
      "title": "sh 文件",
      "frontmatter": {},
      "regularPath": "/blog/Operation-Maintenance/Shell/Base-File.html",
      "relativePath": "blog/Operation-Maintenance/Shell/Base-File.md",
      "key": "v-0a3ba1ca",
      "path": "/blog/Operation-Maintenance/Shell/Base-File.html",
      "headers": [
        {
          "level": 2,
          "title": "sh脚本",
          "slug": "sh脚本"
        }
      ]
    },
    {
      "title": "OS",
      "frontmatter": {},
      "regularPath": "/blog/Operation-Maintenance/OS/Menu.html",
      "relativePath": "blog/Operation-Maintenance/OS/Menu.md",
      "key": "v-475949a8",
      "path": "/blog/Operation-Maintenance/OS/Menu.html"
    },
    {
      "title": "Linux 命令",
      "frontmatter": {},
      "regularPath": "/blog/Operation-Maintenance/Shell/Linux-Shell.html",
      "relativePath": "blog/Operation-Maintenance/Shell/Linux-Shell.md",
      "key": "v-034e2f4c",
      "path": "/blog/Operation-Maintenance/Shell/Linux-Shell.html",
      "headers": [
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 2,
          "title": "ssh",
          "slug": "ssh"
        },
        {
          "level": 3,
          "title": "命令",
          "slug": "命令"
        },
        {
          "level": 3,
          "title": "ssh通过pem文件登陆服务器",
          "slug": "ssh通过pem文件登陆服务器"
        },
        {
          "level": 3,
          "title": "ssh 携带密码登录-sshpass",
          "slug": "ssh-携带密码登录-sshpass"
        },
        {
          "level": 2,
          "title": "查看某个服务的使用情况？",
          "slug": "查看某个服务的使用情况"
        },
        {
          "level": 2,
          "title": "查看某个端口的使用情况？",
          "slug": "查看某个端口的使用情况"
        },
        {
          "level": 2,
          "title": "关闭一个端口",
          "slug": "关闭一个端口"
        },
        {
          "level": 2,
          "title": "创建文件",
          "slug": "创建文件"
        }
      ]
    },
    {
      "title": "Shell",
      "frontmatter": {},
      "regularPath": "/blog/Operation-Maintenance/Shell/Menu.html",
      "relativePath": "blog/Operation-Maintenance/Shell/Menu.md",
      "key": "v-343dee92",
      "path": "/blog/Operation-Maintenance/Shell/Menu.html"
    },
    {
      "title": "Fiddler 抓包工具",
      "frontmatter": {},
      "regularPath": "/blog/Other/Fiddler.html",
      "relativePath": "blog/Other/Fiddler.md",
      "key": "v-2ba3af0a",
      "path": "/blog/Other/Fiddler.html"
    },
    {
      "title": "AR",
      "frontmatter": {},
      "regularPath": "/blog/Other/Live-Stream/AR.html",
      "relativePath": "blog/Other/Live-Stream/AR.md",
      "key": "v-3fbb2552",
      "path": "/blog/Other/Live-Stream/AR.html",
      "headers": [
        {
          "level": 2,
          "title": "AR事例",
          "slug": "ar事例"
        },
        {
          "level": 3,
          "title": "JS快速实验室: 手势控制3D物体",
          "slug": "js快速实验室-手势控制3d物体"
        },
        {
          "level": 3,
          "title": "以实现摄像头精确追踪并识别十指的运动路径/轨迹和手势动作",
          "slug": "以实现摄像头精确追踪并识别十指的运动路径-轨迹和手势动作"
        },
        {
          "level": 3,
          "title": "Handrack.js实现手部识别（手部框）",
          "slug": "handrack-js实现手部识别-手部框"
        },
        {
          "level": 3,
          "title": "可交互内容玩法技术揭秘",
          "slug": "可交互内容玩法技术揭秘"
        },
        {
          "level": 3,
          "title": "Tensorflow JS可识别剪刀石头布三种手势（语言：react+python）",
          "slug": "tensorflow-js可识别剪刀石头布三种手势-语言-react-python"
        },
        {
          "level": 3,
          "title": "Tensorflow 实现手势识别思路",
          "slug": "tensorflow-实现手势识别思路"
        },
        {
          "level": 3,
          "title": "标星 2.3k+，比个手势，AI 自动识别 Emoji！(语言：)",
          "slug": "标星-2-3k-比个手势-ai-自动识别-emoji-语言"
        },
        {
          "level": 2,
          "title": "SDK",
          "slug": "sdk"
        },
        {
          "level": 3,
          "title": "百度AI开发平台",
          "slug": "百度ai开发平台"
        },
        {
          "level": 3,
          "title": "火山引擎",
          "slug": "火山引擎"
        }
      ]
    },
    {
      "title": "JavaCV",
      "frontmatter": {},
      "regularPath": "/blog/Other/Live-Stream/JavaCV.html",
      "relativePath": "blog/Other/Live-Stream/JavaCV.md",
      "key": "v-7579f352",
      "path": "/blog/Other/Live-Stream/JavaCV.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Other/Live-Stream/SRS.html",
      "relativePath": "blog/Other/Live-Stream/SRS.md",
      "key": "v-2b99c4ac",
      "path": "/blog/Other/Live-Stream/SRS.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "主要思想",
          "slug": "主要思想"
        },
        {
          "level": 2,
          "title": "常见语法",
          "slug": "常见语法"
        },
        {
          "level": 2,
          "title": "常见问题",
          "slug": "常见问题"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Other/Live-Stream/WebSocket.html",
      "relativePath": "blog/Other/Live-Stream/WebSocket.md",
      "key": "v-4572fc84",
      "path": "/blog/Other/Live-Stream/WebSocket.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Other/Markdown/Markdown.html",
      "relativePath": "blog/Other/Markdown/Markdown.md",
      "key": "v-13650e50",
      "path": "/blog/Other/Markdown/Markdown.html",
      "headers": [
        {
          "level": 2,
          "title": "Markdown 引用语法",
          "slug": "markdown-引用语法"
        },
        {
          "level": 3,
          "title": "多个段落的块引用",
          "slug": "多个段落的块引用"
        },
        {
          "level": 3,
          "title": "嵌套块引用",
          "slug": "嵌套块引用"
        },
        {
          "level": 3,
          "title": "带有其它元素的块引用",
          "slug": "带有其它元素的块引用"
        },
        {
          "level": 2,
          "title": "Markdown 图片语法",
          "slug": "markdown-图片语法"
        },
        {
          "level": 2,
          "title": "上划线、中划线、下划线",
          "slug": "上划线、中划线、下划线"
        },
        {
          "level": 3,
          "title": "中划线",
          "slug": "中划线"
        },
        {
          "level": 3,
          "title": "下划线",
          "slug": "下划线"
        },
        {
          "level": 3,
          "title": "上划线",
          "slug": "上划线"
        },
        {
          "level": 2,
          "title": "列表",
          "slug": "列表"
        }
      ]
    },
    {
      "title": "好玩应儿就往这堆",
      "frontmatter": {},
      "regularPath": "/blog/Other/Menu.html",
      "relativePath": "blog/Other/Menu.md",
      "key": "v-f5352ddc",
      "path": "/blog/Other/Menu.html"
    },
    {
      "title": "Ngork内网穿透",
      "frontmatter": {},
      "regularPath": "/blog/Other/Ngrok.html",
      "relativePath": "blog/Other/Ngrok.md",
      "key": "v-34fb6368",
      "path": "/blog/Other/Ngrok.html",
      "headers": [
        {
          "level": 2,
          "title": "第一步：注册/登陆Ngork",
          "slug": "第一步-注册-登陆ngork"
        },
        {
          "level": 2,
          "title": "第二步：购买隧道（有免费的）",
          "slug": "第二步-购买隧道-有免费的"
        },
        {
          "level": 2,
          "title": "第三步：下载/使用Ngork客户端",
          "slug": "第三步-下载-使用ngork客户端"
        }
      ]
    },
    {
      "title": "Python",
      "frontmatter": {},
      "regularPath": "/blog/Python/Python-wait.html",
      "relativePath": "blog/Python/Python-wait.md",
      "key": "v-58aaef32",
      "path": "/blog/Python/Python-wait.html"
    },
    {
      "title": "断言",
      "frontmatter": {},
      "regularPath": "/blog/Testing/Test-Common/Assert.html",
      "relativePath": "blog/Testing/Test-Common/Assert.md",
      "key": "v-7fe2e512",
      "path": "/blog/Testing/Test-Common/Assert.html",
      "headers": [
        {
          "level": 2,
          "title": "编写断言的表达式",
          "slug": "编写断言的表达式"
        },
        {
          "level": 3,
          "title": "举个例子",
          "slug": "举个例子"
        },
        {
          "level": 2,
          "title": "运行后没有反应??",
          "slug": "运行后没有反应"
        },
        {
          "level": 2,
          "title": "希望获得更多信息?",
          "slug": "希望获得更多信息"
        },
        {
          "level": 3,
          "title": "举个例子",
          "slug": "举个例子-2"
        },
        {
          "level": 2,
          "title": "前置条件和后置条件",
          "slug": "前置条件和后置条件"
        },
        {
          "level": 3,
          "title": "前置条件",
          "slug": "前置条件"
        },
        {
          "level": 3,
          "title": "后置条件",
          "slug": "后置条件"
        },
        {
          "level": 2,
          "title": "陷阱",
          "slug": "陷阱"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "黑盒测试与白盒测试",
      "frontmatter": {},
      "regularPath": "/blog/Testing/Test-Common/Blackbox-Whitebox.html",
      "relativePath": "blog/Testing/Test-Common/Blackbox-Whitebox.md",
      "key": "v-d384207c",
      "path": "/blog/Testing/Test-Common/Blackbox-Whitebox.html",
      "headers": [
        {
          "level": 2,
          "title": "第一认识",
          "slug": "第一认识"
        },
        {
          "level": 3,
          "title": "黑盒测试",
          "slug": "黑盒测试"
        },
        {
          "level": 3,
          "title": "白盒测试",
          "slug": "白盒测试"
        },
        {
          "level": 2,
          "title": "第二认识",
          "slug": "第二认识"
        },
        {
          "level": 3,
          "title": "黑盒测试",
          "slug": "黑盒测试-2"
        },
        {
          "level": 3,
          "title": "白盒测试",
          "slug": "白盒测试-2"
        },
        {
          "level": 2,
          "title": "第三认识",
          "slug": "第三认识"
        },
        {
          "level": 3,
          "title": "黑盒测试",
          "slug": "黑盒测试-3"
        },
        {
          "level": 3,
          "title": "白盒测试",
          "slug": "白盒测试-3"
        }
      ]
    },
    {
      "title": "SpringCloud 第二季",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Frame/SpringCloud/SpringCloud.html",
      "relativePath": "blog/Java/Java-Frame/SpringCloud/SpringCloud.md",
      "key": "v-2857ea94",
      "path": "/blog/Java/Java-Frame/SpringCloud/SpringCloud.html",
      "headers": [
        {
          "level": 2,
          "title": "1.微服务架构零基础理论入门（小白必看）",
          "slug": "_1-微服务架构零基础理论入门-小白必看"
        },
        {
          "level": 3,
          "title": "回顾2018年第一季SpringCloud版本",
          "slug": "回顾2018年第一季springcloud版本"
        },
        {
          "level": 2,
          "title": "2.从2.2.x和H版开始说起",
          "slug": "_2-从2-2-x和h版开始说起"
        },
        {
          "level": 3,
          "title": "本次的SpringCloud第二季分为上半场和下半场",
          "slug": "本次的springcloud第二季分为上半场和下半场"
        },
        {
          "level": 3,
          "title": "Springboot版本选择",
          "slug": "springboot版本选择"
        },
        {
          "level": 3,
          "title": "SpringCloud版本选择",
          "slug": "springcloud版本选择"
        },
        {
          "level": 3,
          "title": "SpringCloud和Springboot之间的依赖关系如何看",
          "slug": "springcloud和springboot之间的依赖关系如何看"
        },
        {
          "level": 3,
          "title": "SpringCloud第二季定稿版（截止2020.2.15）",
          "slug": "springcloud第二季定稿版-截止2020-2-15"
        },
        {
          "level": 2,
          "title": "3.关于Cloud各种组件的停更/升级/替换",
          "slug": "_3-关于cloud各种组件的停更-升级-替换"
        },
        {
          "level": 3,
          "title": "由停更引发的“升级惨案”",
          "slug": "由停更引发的-升级惨案"
        },
        {
          "level": 3,
          "title": "参考资料见官网",
          "slug": "参考资料见官网"
        },
        {
          "level": 2,
          "title": "4.微服务架构编码构建",
          "slug": "_4-微服务架构编码构建"
        },
        {
          "level": 3,
          "title": "约定 > 配置 > 编码",
          "slug": "约定-配置-编码"
        },
        {
          "level": 3,
          "title": "IDEA新建project工作空间",
          "slug": "idea新建project工作空间"
        },
        {
          "level": 3,
          "title": "Rest微服务工程构建",
          "slug": "rest微服务工程构建"
        },
        {
          "level": 2,
          "title": "5.Eureka服务注册与发现",
          "slug": "_5-eureka服务注册与发现"
        },
        {
          "level": 3,
          "title": "Eureka基础知识",
          "slug": "eureka基础知识"
        },
        {
          "level": 3,
          "title": "单机Eureka构建步骤",
          "slug": "单机eureka构建步骤"
        },
        {
          "level": 3,
          "title": "集群Eureka构建步骤",
          "slug": "集群eureka构建步骤"
        },
        {
          "level": 3,
          "title": "actuator微服务信息完善",
          "slug": "actuator微服务信息完善"
        },
        {
          "level": 3,
          "title": "服务发现Discovery",
          "slug": "服务发现discovery"
        },
        {
          "level": 3,
          "title": "Eureka自我保护",
          "slug": "eureka自我保护"
        },
        {
          "level": 2,
          "title": "6.Zookeeper服务注册与发现",
          "slug": "_6-zookeeper服务注册与发现"
        },
        {
          "level": 3,
          "title": "Eureka停止更新了你怎么办",
          "slug": "eureka停止更新了你怎么办"
        },
        {
          "level": 3,
          "title": "SpringCloud整合Zookeeper代替Eureka",
          "slug": "springcloud整合zookeeper代替eureka"
        },
        {
          "level": 2,
          "title": "7.Consul服务注册与发现",
          "slug": "_7-consul服务注册与发现"
        },
        {
          "level": 3,
          "title": "Consul简介",
          "slug": "consul简介"
        },
        {
          "level": 3,
          "title": "安装并运行Consul",
          "slug": "安装并运行consul"
        },
        {
          "level": 3,
          "title": "服务提供者",
          "slug": "服务提供者"
        },
        {
          "level": 3,
          "title": "服务消费者",
          "slug": "服务消费者"
        },
        {
          "level": 3,
          "title": "三个注册中心异同点",
          "slug": "三个注册中心异同点"
        },
        {
          "level": 2,
          "title": "8.Ribbon负载均衡服务调用",
          "slug": "_8-ribbon负载均衡服务调用"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述"
        },
        {
          "level": 3,
          "title": "Ribbon负载均衡演示",
          "slug": "ribbon负载均衡演示"
        },
        {
          "level": 3,
          "title": "Ribbon核心组件IRule",
          "slug": "ribbon核心组件irule"
        },
        {
          "level": 3,
          "title": "Ribbon负载均衡算法",
          "slug": "ribbon负载均衡算法"
        },
        {
          "level": 2,
          "title": "9.OpenFeign服务接口调用",
          "slug": "_9-openfeign服务接口调用"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述-2"
        },
        {
          "level": 3,
          "title": "OpenFeign使用步骤",
          "slug": "openfeign使用步骤"
        },
        {
          "level": 3,
          "title": "OpenFeign超时控制",
          "slug": "openfeign超时控制"
        },
        {
          "level": 3,
          "title": "OpenFeign日志打印功能",
          "slug": "openfeign日志打印功能"
        },
        {
          "level": 2,
          "title": "10.Hystrix断路器",
          "slug": "_10-hystrix断路器"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述-3"
        },
        {
          "level": 3,
          "title": "Hystrix重要概念",
          "slug": "hystrix重要概念"
        },
        {
          "level": 3,
          "title": "hystrix案例",
          "slug": "hystrix案例"
        },
        {
          "level": 3,
          "title": "hystrix工作流程",
          "slug": "hystrix工作流程"
        },
        {
          "level": 3,
          "title": "服务监控hystrixDashboard",
          "slug": "服务监控hystrixdashboard"
        },
        {
          "level": 2,
          "title": "11.zuul路由网关（没讲）",
          "slug": "_11-zuul路由网关-没讲"
        },
        {
          "level": 2,
          "title": "12.Gateway新一代网关",
          "slug": "_12-gateway新一代网关"
        },
        {
          "level": 3,
          "title": "概述简介",
          "slug": "概述简介"
        },
        {
          "level": 3,
          "title": "三大核心概念",
          "slug": "三大核心概念"
        },
        {
          "level": 3,
          "title": "Gateway工作流程",
          "slug": "gateway工作流程"
        },
        {
          "level": 3,
          "title": "入门配置",
          "slug": "入门配置"
        },
        {
          "level": 3,
          "title": "通过微服务名实现动态路由",
          "slug": "通过微服务名实现动态路由"
        },
        {
          "level": 3,
          "title": "Predicate的使用",
          "slug": "predicate的使用"
        },
        {
          "level": 3,
          "title": "Filter的使用",
          "slug": "filter的使用"
        },
        {
          "level": 2,
          "title": "13.SpringCloud config分布式配置中心",
          "slug": "_13-springcloud-config分布式配置中心"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述-4"
        },
        {
          "level": 3,
          "title": "Config服务端配置与测试",
          "slug": "config服务端配置与测试"
        },
        {
          "level": 3,
          "title": "Config客户端配置与测试",
          "slug": "config客户端配置与测试"
        },
        {
          "level": 3,
          "title": "Config客户端之动态刷新",
          "slug": "config客户端之动态刷新"
        },
        {
          "level": 2,
          "title": "14.SpringCloud Bus 消息总线",
          "slug": "_14-springcloud-bus-消息总线"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述-5"
        },
        {
          "level": 3,
          "title": "RabbitMQ环境配置",
          "slug": "rabbitmq环境配置"
        },
        {
          "level": 3,
          "title": "SpringCloud Bus动态刷新全局广播",
          "slug": "springcloud-bus动态刷新全局广播"
        },
        {
          "level": 3,
          "title": "SpringCloud Bus动态刷新定点通知",
          "slug": "springcloud-bus动态刷新定点通知"
        },
        {
          "level": 2,
          "title": "15.SpringCloud Stream消息驱动",
          "slug": "_15-springcloud-stream消息驱动"
        },
        {
          "level": 3,
          "title": "消息驱动概述",
          "slug": "消息驱动概述"
        },
        {
          "level": 3,
          "title": "案例说明",
          "slug": "案例说明"
        },
        {
          "level": 3,
          "title": "消息驱动之生产者",
          "slug": "消息驱动之生产者"
        },
        {
          "level": 3,
          "title": "消息驱动之消费者",
          "slug": "消息驱动之消费者"
        },
        {
          "level": 3,
          "title": "分组消费与持久化",
          "slug": "分组消费与持久化"
        },
        {
          "level": 2,
          "title": "16.SpringCloud Sleuth分布式请求链路追踪",
          "slug": "_16-springcloud-sleuth分布式请求链路追踪"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述-6"
        },
        {
          "level": 3,
          "title": "搭建链路监控步骤",
          "slug": "搭建链路监控步骤"
        },
        {
          "level": 2,
          "title": "17.SpringCloud Alibaba入门简介",
          "slug": "_17-springcloud-alibaba入门简介"
        },
        {
          "level": 3,
          "title": "why会出现SpringCloud alibaba",
          "slug": "why会出现springcloud-alibaba"
        },
        {
          "level": 3,
          "title": "SpringCloud alibaba带来了什么？",
          "slug": "springcloud-alibaba带来了什么"
        },
        {
          "level": 3,
          "title": "SpringCloud alibaba学习资料获取",
          "slug": "springcloud-alibaba学习资料获取"
        },
        {
          "level": 2,
          "title": "18.SpringCloud Alibaba Nacos服务注册和配置中心",
          "slug": "_18-springcloud-alibaba-nacos服务注册和配置中心"
        },
        {
          "level": 3,
          "title": "Nacos简介",
          "slug": "nacos简介"
        },
        {
          "level": 3,
          "title": "安装并运行Nacos",
          "slug": "安装并运行nacos"
        },
        {
          "level": 3,
          "title": "Nacos作为服务注册中心演示",
          "slug": "nacos作为服务注册中心演示"
        },
        {
          "level": 3,
          "title": "Nacos作为服务配置中心演示",
          "slug": "nacos作为服务配置中心演示"
        },
        {
          "level": 3,
          "title": "Nacos集群和持久化配置（重要）",
          "slug": "nacos集群和持久化配置-重要"
        },
        {
          "level": 2,
          "title": "19.SpringCloud Alibaba Sentinel实现熔断与限流",
          "slug": "_19-springcloud-alibaba-sentinel实现熔断与限流"
        },
        {
          "level": 3,
          "title": "Sentinel",
          "slug": "sentinel"
        },
        {
          "level": 3,
          "title": "安装Sentinel控制台",
          "slug": "安装sentinel控制台"
        },
        {
          "level": 3,
          "title": "初始化演示工程",
          "slug": "初始化演示工程"
        },
        {
          "level": 3,
          "title": "流控规则",
          "slug": "流控规则"
        },
        {
          "level": 3,
          "title": "降级规则",
          "slug": "降级规则"
        },
        {
          "level": 3,
          "title": "热点key限流",
          "slug": "热点key限流"
        },
        {
          "level": 3,
          "title": "系统规则",
          "slug": "系统规则"
        },
        {
          "level": 3,
          "title": "@SentinelResource",
          "slug": "sentinelresource"
        },
        {
          "level": 3,
          "title": "服务熔断功能",
          "slug": "服务熔断功能"
        },
        {
          "level": 3,
          "title": "规则持久化",
          "slug": "规则持久化"
        },
        {
          "level": 2,
          "title": "20.SpringCloud Alibaba Seata处理分布式事务",
          "slug": "_20-springcloud-alibaba-seata处理分布式事务"
        },
        {
          "level": 3,
          "title": "分布式事务问题",
          "slug": "分布式事务问题"
        },
        {
          "level": 3,
          "title": "Seata简介",
          "slug": "seata简介"
        },
        {
          "level": 3,
          "title": "Seata-Server安装",
          "slug": "seata-server安装"
        },
        {
          "level": 3,
          "title": "订单/库存/账户业务数据库准备",
          "slug": "订单-库存-账户业务数据库准备"
        },
        {
          "level": 3,
          "title": "订单/库存/账户业务微服务准备",
          "slug": "订单-库存-账户业务微服务准备"
        },
        {
          "level": 3,
          "title": "Test",
          "slug": "test"
        },
        {
          "level": 3,
          "title": "Seata之原理简介",
          "slug": "seata之原理简介"
        }
      ]
    },
    {
      "title": "TestNG",
      "frontmatter": {},
      "regularPath": "/blog/Testing/TestNG/Menu.html",
      "relativePath": "blog/Testing/TestNG/Menu.md",
      "key": "v-0e8a4bb0",
      "path": "/blog/Testing/TestNG/Menu.html"
    },
    {
      "title": "TestNG 基本注解",
      "frontmatter": {},
      "regularPath": "/blog/Testing/TestNG/TestNG-Annotation.html",
      "relativePath": "blog/Testing/TestNG/TestNG-Annotation.md",
      "key": "v-53769112",
      "path": "/blog/Testing/TestNG/TestNG-Annotation.html",
      "headers": [
        {
          "level": 2,
          "title": "注解列表",
          "slug": "注解列表"
        },
        {
          "level": 2,
          "title": "忽略测试",
          "slug": "忽略测试"
        },
        {
          "level": 2,
          "title": "超时处理",
          "slug": "超时处理"
        },
        {
          "level": 2,
          "title": "使用注释/注解的好处",
          "slug": "使用注释-注解的好处"
        }
      ]
    },
    {
      "title": "测试相关概念",
      "frontmatter": {},
      "regularPath": "/blog/Testing/Test-Common/Menu.html",
      "relativePath": "blog/Testing/Test-Common/Menu.md",
      "key": "v-2824a29c",
      "path": "/blog/Testing/Test-Common/Menu.html"
    },
    {
      "title": "TestNG - DataProvider（注解）数据提供者",
      "frontmatter": {},
      "regularPath": "/blog/Testing/TestNG/TestNG-DataProvider.html",
      "relativePath": "blog/Testing/TestNG/TestNG-DataProvider.md",
      "key": "v-53f61452",
      "path": "/blog/Testing/TestNG/TestNG-DataProvider.html",
      "headers": [
        {
          "level": 2,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 2,
          "title": "备注",
          "slug": "备注"
        },
        {
          "level": 3,
          "title": "注解使用",
          "slug": "注解使用"
        },
        {
          "level": 3,
          "title": "返回结构Object[][]",
          "slug": "返回结构object"
        },
        {
          "level": 2,
          "title": "提供数据方式",
          "slug": "提供数据方式"
        }
      ]
    },
    {
      "title": "TestNG 使用",
      "frontmatter": {},
      "regularPath": "/blog/Testing/TestNG/TestNG-Init.html",
      "relativePath": "blog/Testing/TestNG/TestNG-Init.md",
      "key": "v-9334f51c",
      "path": "/blog/Testing/TestNG/TestNG-Init.html",
      "headers": [
        {
          "level": 2,
          "title": "maven",
          "slug": "maven"
        },
        {
          "level": 2,
          "title": "概念",
          "slug": "概念"
        }
      ]
    },
    {
      "title": "工具箱",
      "frontmatter": {},
      "regularPath": "/blog/Tool/Menu.html",
      "relativePath": "blog/Tool/Menu.md",
      "key": "v-3efc10e8",
      "path": "/blog/Tool/Menu.html"
    },
    {
      "title": "可参考内容",
      "frontmatter": {},
      "regularPath": "/blog/Web/Android/Reference.html",
      "relativePath": "blog/Web/Android/Reference.md",
      "key": "v-28c37658",
      "path": "/blog/Web/Android/Reference.html"
    },
    {
      "title": "安卓应用开发",
      "frontmatter": {},
      "regularPath": "/blog/Web/Android/Menu.html",
      "relativePath": "blog/Web/Android/Menu.md",
      "key": "v-9f9f295c",
      "path": "/blog/Web/Android/Menu.html"
    },
    {
      "title": "CSS",
      "frontmatter": {},
      "regularPath": "/blog/Web/CSS/CSS.html",
      "relativePath": "blog/Web/CSS/CSS.md",
      "key": "v-61d2a000",
      "path": "/blog/Web/CSS/CSS.html",
      "headers": [
        {
          "level": 2,
          "title": "常见场景",
          "slug": "常见场景"
        }
      ]
    },
    {
      "title": "CSS",
      "frontmatter": {},
      "regularPath": "/blog/Web/CSS/Menu.html",
      "relativePath": "blog/Web/CSS/Menu.md",
      "key": "v-413d415c",
      "path": "/blog/Web/CSS/Menu.html"
    },
    {
      "title": "IDE",
      "frontmatter": {},
      "regularPath": "/blog/Web/IDE/Menu.html",
      "relativePath": "blog/Web/IDE/Menu.md",
      "key": "v-7b0025b2",
      "path": "/blog/Web/IDE/Menu.html"
    },
    {
      "title": "vscode",
      "frontmatter": {},
      "regularPath": "/blog/Web/IDE/VSCode.html",
      "relativePath": "blog/Web/IDE/VSCode.md",
      "key": "v-8725bddc",
      "path": "/blog/Web/IDE/VSCode.html"
    },
    {
      "title": "js post方式打开新窗口",
      "frontmatter": {},
      "regularPath": "/blog/Web/JS/JS-Window.html",
      "relativePath": "blog/Web/JS/JS-Window.md",
      "key": "v-3fc6ef1c",
      "path": "/blog/Web/JS/JS-Window.html",
      "headers": [
        {
          "level": 2,
          "title": "html",
          "slug": "html"
        },
        {
          "level": 2,
          "title": "接口",
          "slug": "接口"
        }
      ]
    },
    {
      "title": "ES6的export与Nodejs的module.exports",
      "frontmatter": {},
      "regularPath": "/blog/Web/JS/JS-Module-Specification.html",
      "relativePath": "blog/Web/JS/JS-Module-Specification.md",
      "key": "v-24c5579c",
      "path": "/blog/Web/JS/JS-Module-Specification.html",
      "headers": [
        {
          "level": 2,
          "title": "CommonJS模块规范",
          "slug": "commonjs模块规范"
        },
        {
          "level": 3,
          "title": "exports 与 module.exports",
          "slug": "exports-与-module-exports"
        },
        {
          "level": 2,
          "title": "ES6模块规范",
          "slug": "es6模块规范"
        },
        {
          "level": 3,
          "title": "export default 命令",
          "slug": "export-default-命令"
        }
      ]
    },
    {
      "title": "JS",
      "frontmatter": {},
      "regularPath": "/blog/Web/JS/Menu.html",
      "relativePath": "blog/Web/JS/Menu.md",
      "key": "v-636b76e4",
      "path": "/blog/Web/JS/Menu.html"
    },
    {
      "title": "Vue",
      "frontmatter": {},
      "regularPath": "/blog/Web/Vue/Menu.html",
      "relativePath": "blog/Web/Vue/Menu.md",
      "key": "v-37a3319c",
      "path": "/blog/Web/Vue/Menu.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Web/Vue/Vue.html",
      "relativePath": "blog/Web/Vue/Vue.md",
      "key": "v-87f7c918",
      "path": "/blog/Web/Vue/Vue.html"
    },
    {
      "title": "vuepress",
      "frontmatter": {},
      "regularPath": "/blog/Web/Vue/Vuepress.html",
      "relativePath": "blog/Web/Vue/Vuepress.md",
      "key": "v-564fb572",
      "path": "/blog/Web/Vue/Vuepress.html",
      "headers": [
        {
          "level": 2,
          "title": "基础了解",
          "slug": "基础了解"
        },
        {
          "level": 2,
          "title": "遇见过的问题",
          "slug": "遇见过的问题"
        }
      ]
    },
    {
      "title": "文档目录思路",
      "frontmatter": {},
      "regularPath": "/blog/up_up_up.html",
      "relativePath": "blog/up_up_up.md",
      "key": "v-cfd53f9c",
      "path": "/blog/up_up_up.html",
      "headers": [
        {
          "level": 2,
          "title": "目录优化",
          "slug": "目录优化"
        },
        {
          "level": 2,
          "title": "主体思路",
          "slug": "主体思路"
        }
      ]
    },
    {
      "title": "分布式",
      "frontmatter": {},
      "regularPath": "/blog/%E6%A6%82%E5%BF%B5%E6%A2%B3%E7%90%86.html",
      "relativePath": "blog/概念梳理.md",
      "key": "v-fe71cd72",
      "path": "/blog/%E6%A6%82%E5%BF%B5%E6%A2%B3%E7%90%86.html",
      "headers": [
        {
          "level": 2,
          "title": "分布式",
          "slug": "分布式"
        },
        {
          "level": 2,
          "title": "微服务",
          "slug": "微服务"
        },
        {
          "level": 2,
          "title": "SAAS",
          "slug": "saas"
        }
      ]
    }
  ],
  "themeConfig": {
    "repo": "https://gitee.com/guoshunfa",
    "repoLabel": "Gitee",
    "sidebar": "auto",
    "nav": [
      {
        "text": "Java",
        "items": [
          {
            "text": "Java 基础",
            "link": "/blog/Java/Common/Menu.md"
          },
          {
            "text": "Java 框架",
            "link": "/blog/Java/Java-Frame/Menu.md"
          },
          {
            "text": "Java 学习工具",
            "link": "/blog/Java/Tool/Menu.md"
          }
        ]
      },
      {
        "text": "数据库",
        "items": [
          {
            "text": "MongoDB",
            "link": "/blog/Database/MongoDB/Menu.md"
          },
          {
            "text": "Mysql",
            "link": "/blog/Database/Mysql/Menu.md"
          },
          {
            "text": "Redis",
            "link": "/blog/Database/Redis/Menu.md"
          },
          {
            "text": "其他",
            "link": "/blog/Database/Other/Menu.md"
          }
        ]
      },
      {
        "text": "运维",
        "items": [
          {
            "text": "OS",
            "link": "/blog/Operation-Maintenance/OS/Menu.md"
          },
          {
            "text": "Shell",
            "link": "/blog/Operation-Maintenance/Shell/Menu.md"
          },
          {
            "text": "Docker",
            "link": "/blog/Operation-Maintenance/Docker/Menu.md"
          }
        ]
      },
      {
        "text": "测试",
        "items": [
          {
            "text": "概念",
            "link": "/blog/Testing/Test-Common/Menu.md"
          },
          {
            "text": "testng 框架",
            "link": "/blog/Testing/TestNG/Menu.md"
          }
        ]
      },
      {
        "text": "Web",
        "items": [
          {
            "text": "JS",
            "link": "/blog/Web/JS/Menu.md"
          },
          {
            "text": "CSS",
            "link": "/blog/Web/CSS/Menu.md"
          },
          {
            "text": "Vue",
            "link": "/blog/Web/Vue/Menu.md"
          },
          {
            "text": "IDE",
            "link": "/blog/Web/IDE/Menu.md"
          },
          {
            "text": "Android",
            "link": "/blog/Web/Android/Menu.md"
          }
        ]
      },
      {
        "text": "Python",
        "link": "/blog/Python/Python-wait.md"
      },
      {
        "text": "工具箱",
        "link": "/blog/Tool/Menu.md"
      }
    ]
  }
}