/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/document-backup/",
  "headTags": [],
  "pages": [
    {
      "title": "达梦数据库",
      "frontmatter": {},
      "regularPath": "/blog/Database/DM/DM.html",
      "relativePath": "blog/Database/DM/DM.md",
      "key": "v-50c65d7c",
      "path": "/blog/Database/DM/DM.html",
      "headers": [
        {
          "level": 3,
          "title": "mysql数据库转达梦数据库方法",
          "slug": "mysql数据库转达梦数据库方法"
        },
        {
          "level": 3,
          "title": "达梦数据库 无效的表或试图名问题",
          "slug": "达梦数据库-无效的表或试图名问题"
        },
        {
          "level": 3,
          "title": "达梦数据库SQL指南",
          "slug": "达梦数据库sql指南"
        },
        {
          "level": 3,
          "title": "达梦数据库常用sql语句",
          "slug": "达梦数据库常用sql语句"
        }
      ]
    },
    {
      "title": "安装Mongodb",
      "frontmatter": {},
      "regularPath": "/blog/Database/MongoDB/MongoDB-Init.html",
      "relativePath": "blog/Database/MongoDB/MongoDB-Init.md",
      "key": "v-705c290a",
      "path": "/blog/Database/MongoDB/MongoDB-Init.html",
      "headers": [
        {
          "level": 2,
          "title": "MAC OSX平台安装MongdoDB",
          "slug": "mac-osx平台安装mongdodb"
        },
        {
          "level": 2,
          "title": "使用 brew 安装",
          "slug": "使用-brew-安装"
        }
      ]
    },
    {
      "title": "Mongodb - 表达式操作符",
      "frontmatter": {},
      "regularPath": "/blog/Database/MongoDB/MongoDB-Expression.html",
      "relativePath": "blog/Database/MongoDB/MongoDB-Expression.md",
      "key": "v-9974b88c",
      "path": "/blog/Database/MongoDB/MongoDB-Expression.html",
      "headers": [
        {
          "level": 2,
          "title": "表达式操作符（Expression Operators）",
          "slug": "表达式操作符-expression-operators"
        },
        {
          "level": 3,
          "title": "表达式操作符分类",
          "slug": "表达式操作符分类"
        },
        {
          "level": 3,
          "title": "常用表达式操作符",
          "slug": "常用表达式操作符"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "熊猫 文档存储",
        "tagline": null
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-78aea302",
      "path": "/"
    },
    {
      "title": "MongoDB",
      "frontmatter": {},
      "regularPath": "/blog/Database/MongoDB/MongoDB-Wait.html",
      "relativePath": "blog/Database/MongoDB/MongoDB-Wait.md",
      "key": "v-4746da40",
      "path": "/blog/Database/MongoDB/MongoDB-Wait.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "常见命令",
          "slug": "常见命令"
        }
      ]
    },
    {
      "title": "Mysql 控制台使用说明",
      "frontmatter": {},
      "regularPath": "/blog/Database/Mysql/Mysql-Console.html",
      "relativePath": "blog/Database/Mysql/Mysql-Console.md",
      "key": "v-3b15c47c",
      "path": "/blog/Database/Mysql/Mysql-Console.html",
      "headers": [
        {
          "level": 2,
          "title": "进入控制台",
          "slug": "进入控制台"
        },
        {
          "level": 2,
          "title": "提示符信息",
          "slug": "提示符信息"
        },
        {
          "level": 2,
          "title": "客户端帮助",
          "slug": "客户端帮助"
        }
      ]
    },
    {
      "title": "MongoDB shell语法",
      "frontmatter": {},
      "regularPath": "/blog/Database/MongoDB/MongoDB-Shell.html",
      "relativePath": "blog/Database/MongoDB/MongoDB-Shell.md",
      "key": "v-c431ecc8",
      "path": "/blog/Database/MongoDB/MongoDB-Shell.html",
      "headers": [
        {
          "level": 2,
          "title": "命令行选项",
          "slug": "命令行选项"
        },
        {
          "level": 2,
          "title": "命令助手",
          "slug": "命令助手"
        },
        {
          "level": 2,
          "title": "Shell JavaScript基本操作",
          "slug": "shell-javascript基本操作"
        },
        {
          "level": 2,
          "title": "查询",
          "slug": "查询"
        },
        {
          "level": 2,
          "title": "错误检查方法",
          "slug": "错误检查方法"
        },
        {
          "level": 2,
          "title": "管理命令助手",
          "slug": "管理命令助手"
        },
        {
          "level": 2,
          "title": "打开附加连接",
          "slug": "打开附加连接"
        },
        {
          "level": 2,
          "title": "杂项",
          "slug": "杂项"
        },
        {
          "level": 2,
          "title": "其他资源",
          "slug": "其他资源"
        }
      ]
    },
    {
      "title": "MongoDB 执行JS脚本",
      "frontmatter": {},
      "regularPath": "/blog/Database/MongoDB/MongoDB-Script.html",
      "relativePath": "blog/Database/MongoDB/MongoDB-Script.md",
      "key": "v-1da76794",
      "path": "/blog/Database/MongoDB/MongoDB-Script.html",
      "headers": [
        {
          "level": 2,
          "title": "脚本执行方法",
          "slug": "脚本执行方法"
        },
        {
          "level": 2,
          "title": "语法",
          "slug": "语法"
        },
        {
          "level": 3,
          "title": "数据库连接相关语法",
          "slug": "数据库连接相关语法"
        },
        {
          "level": 3,
          "title": "日志打印语法",
          "slug": "日志打印语法"
        }
      ]
    },
    {
      "title": "Mysql 常见的错误",
      "frontmatter": {},
      "regularPath": "/blog/Database/Mysql/Mysql-Error.html",
      "relativePath": "blog/Database/Mysql/Mysql-Error.md",
      "key": "v-ba2109c8",
      "path": "/blog/Database/Mysql/Mysql-Error.html",
      "headers": [
        {
          "level": 2,
          "title": "Error Code: 1175. You are using safe update",
          "slug": "error-code-1175-you-are-using-safe-update"
        },
        {
          "level": 2,
          "title": "mysql解决只能用localhost连接,不能用ip连接的问题",
          "slug": "mysql解决只能用localhost连接-不能用ip连接的问题"
        }
      ]
    },
    {
      "title": "Mysql 常用sql",
      "frontmatter": {},
      "regularPath": "/blog/Database/Mysql/Mysql-SQL.html",
      "relativePath": "blog/Database/Mysql/Mysql-SQL.md",
      "key": "v-27cccf9c",
      "path": "/blog/Database/Mysql/Mysql-SQL.html"
    },
    {
      "title": "安装Mysql",
      "frontmatter": {},
      "regularPath": "/blog/Database/Mysql/Mysql-Init.html",
      "relativePath": "blog/Database/Mysql/Mysql-Init.md",
      "key": "v-3a2a80ca",
      "path": "/blog/Database/Mysql/Mysql-Init.html",
      "headers": [
        {
          "level": 2,
          "title": "Mac OSX 安装Mysql",
          "slug": "mac-osx-安装mysql"
        }
      ]
    },
    {
      "title": "Workbench 使用说明",
      "frontmatter": {},
      "regularPath": "/blog/Database/Mysql/Mysql-Workbench.html",
      "relativePath": "blog/Database/Mysql/Mysql-Workbench.md",
      "key": "v-de30d708",
      "path": "/blog/Database/Mysql/Mysql-Workbench.html",
      "headers": [
        {
          "level": 3,
          "title": "MySQL Workbench导出数据库",
          "slug": "mysql-workbench导出数据库"
        }
      ]
    },
    {
      "title": "Redis 安装/服务暂停与启动",
      "frontmatter": {},
      "regularPath": "/blog/Database/Redis/Redis-Init.html",
      "relativePath": "blog/Database/Redis/Redis-Init.md",
      "key": "v-490cdd2e",
      "path": "/blog/Database/Redis/Redis-Init.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        }
      ]
    },
    {
      "title": "自我介绍",
      "frontmatter": {},
      "regularPath": "/blog/Interview/Foremost/%E8%AF%9D%E6%9C%AF/%E8%87%AA%E6%88%91%E4%BB%8B%E7%BB%8D.html",
      "relativePath": "blog/Interview/Foremost/话术/自我介绍.md",
      "key": "v-5b280128",
      "path": "/blog/Interview/Foremost/%E8%AF%9D%E6%9C%AF/%E8%87%AA%E6%88%91%E4%BB%8B%E7%BB%8D.html",
      "headers": [
        {
          "level": 2,
          "title": "思路",
          "slug": "思路"
        },
        {
          "level": 2,
          "title": "将思路串起来",
          "slug": "将思路串起来"
        },
        {
          "level": 2,
          "title": "完整的结果",
          "slug": "完整的结果"
        }
      ]
    },
    {
      "title": "简历 概要说明",
      "frontmatter": {},
      "regularPath": "/blog/Interview/Foremost/%E7%AE%80%E5%8E%86/%E7%AE%80%E5%8E%86%20%E6%A6%82%E8%A6%81%E8%AF%B4%E6%98%8E.html",
      "relativePath": "blog/Interview/Foremost/简历/简历 概要说明.md",
      "key": "v-5b405880",
      "path": "/blog/Interview/Foremost/%E7%AE%80%E5%8E%86/%E7%AE%80%E5%8E%86%20%E6%A6%82%E8%A6%81%E8%AF%B4%E6%98%8E.html"
    },
    {
      "title": "Linux 面试常见问题",
      "frontmatter": {},
      "regularPath": "/blog/Interview/Foremost/%E9%9D%A2%E8%AF%95%E9%97%AE%E9%A2%98/Linux.html",
      "relativePath": "blog/Interview/Foremost/面试问题/Linux.md",
      "key": "v-f5b84302",
      "path": "/blog/Interview/Foremost/%E9%9D%A2%E8%AF%95%E9%97%AE%E9%A2%98/Linux.html"
    },
    {
      "title": "int和Integer的区别",
      "frontmatter": {},
      "regularPath": "/blog/Interview/Java/Int-Integer.html",
      "relativePath": "blog/Interview/Java/Int-Integer.md",
      "key": "v-7544693c",
      "path": "/blog/Interview/Java/Int-Integer.html"
    },
    {
      "title": "idea",
      "frontmatter": {},
      "regularPath": "/blog/Java-Frame/IDE/IDEA-Wait.html",
      "relativePath": "blog/Java-Frame/IDE/IDEA-Wait.md",
      "key": "v-9571fe88",
      "path": "/blog/Java-Frame/IDE/IDEA-Wait.html",
      "headers": [
        {
          "level": 2,
          "title": "常用操作",
          "slug": "常用操作"
        },
        {
          "level": 2,
          "title": "常见问题",
          "slug": "常见问题"
        },
        {
          "level": 2,
          "title": "常用快捷键",
          "slug": "常用快捷键"
        },
        {
          "level": 3,
          "title": "Idea mac 自动补全函数返回值快捷键",
          "slug": "idea-mac-自动补全函数返回值快捷键"
        },
        {
          "level": 3,
          "title": "idea格式化代码快捷键",
          "slug": "idea格式化代码快捷键"
        }
      ]
    },
    {
      "title": "智慧环卫项目介绍",
      "frontmatter": {},
      "regularPath": "/blog/Interview/Foremost/%E9%A1%B9%E7%9B%AE%E4%BB%8B%E7%BB%8D/%E6%99%BA%E6%85%A7%E7%8E%AF%E5%8D%AB%E4%B8%9A%E5%8A%A1%E6%94%AF%E6%92%91%E7%B3%BB%E7%BB%9F.html",
      "relativePath": "blog/Interview/Foremost/项目介绍/智慧环卫业务支撑系统.md",
      "key": "v-04a20994",
      "path": "/blog/Interview/Foremost/%E9%A1%B9%E7%9B%AE%E4%BB%8B%E7%BB%8D/%E6%99%BA%E6%85%A7%E7%8E%AF%E5%8D%AB%E4%B8%9A%E5%8A%A1%E6%94%AF%E6%92%91%E7%B3%BB%E7%BB%9F.html",
      "headers": [
        {
          "level": 2,
          "title": "垃圾收费模块（主要描述）",
          "slug": "垃圾收费模块-主要描述"
        },
        {
          "level": 2,
          "title": "垃圾收运模块",
          "slug": "垃圾收运模块"
        },
        {
          "level": 2,
          "title": "垃圾分类模块",
          "slug": "垃圾分类模块"
        }
      ]
    },
    {
      "title": "String、StringBuffer、StringBuilder的区别",
      "frontmatter": {},
      "regularPath": "/blog/Interview/Java/String-Stringbuffer-Stringbuiler.html",
      "relativePath": "blog/Interview/Java/String-Stringbuffer-Stringbuiler.md",
      "key": "v-49d57e1c",
      "path": "/blog/Interview/Java/String-Stringbuffer-Stringbuiler.html",
      "headers": [
        {
          "level": 3,
          "title": "String、StringBuffer、StringBuilder的区别：",
          "slug": "string、stringbuffer、stringbuilder的区别-2"
        },
        {
          "level": 3,
          "title": "String：",
          "slug": "string"
        },
        {
          "level": 3,
          "title": "StringBuffer：（效率不如StringBuilder，但远比String要高）",
          "slug": "stringbuffer-效率不如stringbuilder-但远比string要高"
        },
        {
          "level": 3,
          "title": "StringBuilder：（没有考虑线程安全问题）",
          "slug": "stringbuilder-没有考虑线程安全问题"
        }
      ]
    },
    {
      "title": "java 创建线程的三种方式、创建线程池的四种方式",
      "frontmatter": {},
      "regularPath": "/blog/Interview/Java/Thread.html",
      "relativePath": "blog/Interview/Java/Thread.md",
      "key": "v-4e419820",
      "path": "/blog/Interview/Java/Thread.html",
      "headers": [
        {
          "level": 2,
          "title": "概要：",
          "slug": "概要"
        },
        {
          "level": 2,
          "title": "第一 Java中创建线程主要有三种方式：",
          "slug": "第一-java中创建线程主要有三种方式"
        },
        {
          "level": 3,
          "title": "1、继承Thread类创建线程类 （extends）",
          "slug": "_1、继承thread类创建线程类-extends"
        },
        {
          "level": 3,
          "title": "2、通过Runnable接口创建线程类",
          "slug": "_2、通过runnable接口创建线程类"
        },
        {
          "level": 3,
          "title": "3、通过Callable和Future创建线程",
          "slug": "_3、通过callable和future创建线程"
        },
        {
          "level": 2,
          "title": "二、创建线程的三种方式的对比",
          "slug": "二、创建线程的三种方式的对比"
        }
      ]
    },
    {
      "title": "spring event",
      "frontmatter": {},
      "regularPath": "/blog/Java-Frame/Spring/Spring-Event.html",
      "relativePath": "blog/Java-Frame/Spring/Spring-Event.md",
      "key": "v-415c23fc",
      "path": "/blog/Java-Frame/Spring/Spring-Event.html",
      "headers": [
        {
          "level": 2,
          "title": "spring event",
          "slug": "spring-event"
        },
        {
          "level": 3,
          "title": "1. 自定义Event",
          "slug": "_1-自定义event"
        },
        {
          "level": 3,
          "title": "2. 监听器",
          "slug": "_2-监听器"
        },
        {
          "level": 3,
          "title": "3. 消息发布者",
          "slug": "_3-消息发布者"
        },
        {
          "level": 3,
          "title": "4. 测试方法",
          "slug": "_4-测试方法"
        },
        {
          "level": 3,
          "title": "5. 结果",
          "slug": "_5-结果"
        },
        {
          "level": 3,
          "title": "6. 示例源码",
          "slug": "_6-示例源码"
        },
        {
          "level": 3,
          "title": "7. 扩展 - 监听事件时的事务隔离",
          "slug": "_7-扩展-监听事件时的事务隔离"
        }
      ]
    },
    {
      "title": "Quartz 使用",
      "frontmatter": {},
      "regularPath": "/blog/Java-Frame/Quartz/Quartz-init.html",
      "relativePath": "blog/Java-Frame/Quartz/Quartz-init.md",
      "key": "v-44be7e4c",
      "path": "/blog/Java-Frame/Quartz/Quartz-init.html"
    },
    {
      "title": "IDEA 使用说明",
      "frontmatter": {},
      "regularPath": "/blog/Java-Frame/IDE/IDEA.html",
      "relativePath": "blog/Java-Frame/IDE/IDEA.md",
      "key": "v-fb277ca0",
      "path": "/blog/Java-Frame/IDE/IDEA.html",
      "headers": [
        {
          "level": 2,
          "title": "如何将Spring Boot打成war包",
          "slug": "如何将spring-boot打成war包"
        }
      ]
    },
    {
      "title": "Spring 参数校验器（Validator）",
      "frontmatter": {},
      "regularPath": "/blog/Java-Frame/Spring/Spring-Validator.html",
      "relativePath": "blog/Java-Frame/Spring/Spring-Validator.md",
      "key": "v-1c5fea08",
      "path": "/blog/Java-Frame/Spring/Spring-Validator.html",
      "headers": [
        {
          "level": 2,
          "title": "JSR-303",
          "slug": "jsr-303"
        },
        {
          "level": 2,
          "title": "用法实例",
          "slug": "用法实例"
        },
        {
          "level": 2,
          "title": "常见的校验注解",
          "slug": "常见的校验注解"
        },
        {
          "level": 2,
          "title": "自定义校验注解",
          "slug": "自定义校验注解"
        },
        {
          "level": 2,
          "title": "额外",
          "slug": "额外"
        },
        {
          "level": 2,
          "title": "最后",
          "slug": "最后"
        }
      ]
    },
    {
      "title": "事务",
      "frontmatter": {},
      "regularPath": "/blog/Java-Frame/Spring/Spring-Transaction.html",
      "relativePath": "blog/Java-Frame/Spring/Spring-Transaction.md",
      "key": "v-7375ab7c",
      "path": "/blog/Java-Frame/Spring/Spring-Transaction.html",
      "headers": [
        {
          "level": 2,
          "title": "事务",
          "slug": "事务"
        },
        {
          "level": 3,
          "title": "事务操作（事务概念）",
          "slug": "事务操作-事务概念"
        },
        {
          "level": 3,
          "title": "事务操作（搭建事务操作环境）",
          "slug": "事务操作-搭建事务操作环境"
        },
        {
          "level": 3,
          "title": "事务操作（ Spring 事务管理介绍）",
          "slug": "事务操作-spring-事务管理介绍"
        },
        {
          "level": 3,
          "title": "事务操作（注解声明式事务管理）",
          "slug": "事务操作-注解声明式事务管理"
        },
        {
          "level": 3,
          "title": "事务操作（声明式事务管理参数配置）",
          "slug": "事务操作-声明式事务管理参数配置"
        },
        {
          "level": 3,
          "title": "事务操作（ XML 声明式事务管理）",
          "slug": "事务操作-xml-声明式事务管理"
        },
        {
          "level": 3,
          "title": "事务操作（完全注解声明式事务管理）",
          "slug": "事务操作-完全注解声明式事务管理"
        }
      ]
    },
    {
      "title": "Tomcat 启动web项目使用说明",
      "frontmatter": {},
      "regularPath": "/blog/Java-Frame/Tomcat/Tomcat-web.html",
      "relativePath": "blog/Java-Frame/Tomcat/Tomcat-web.md",
      "key": "v-357e65bc",
      "path": "/blog/Java-Frame/Tomcat/Tomcat-web.html",
      "headers": [
        {
          "level": 2,
          "title": "引入War包",
          "slug": "引入war包"
        }
      ]
    },
    {
      "title": "SpringCloud 第二季",
      "frontmatter": {},
      "regularPath": "/blog/Java-Frame/SpringCloud/SpringCloud.html",
      "relativePath": "blog/Java-Frame/SpringCloud/SpringCloud.md",
      "key": "v-fcfeb5c8",
      "path": "/blog/Java-Frame/SpringCloud/SpringCloud.html",
      "headers": [
        {
          "level": 2,
          "title": "1.微服务架构零基础理论入门（小白必看）",
          "slug": "_1-微服务架构零基础理论入门-小白必看"
        },
        {
          "level": 3,
          "title": "回顾2018年第一季SpringCloud版本",
          "slug": "回顾2018年第一季springcloud版本"
        },
        {
          "level": 2,
          "title": "2.从2.2.x和H版开始说起",
          "slug": "_2-从2-2-x和h版开始说起"
        },
        {
          "level": 3,
          "title": "本次的SpringCloud第二季分为上半场和下半场",
          "slug": "本次的springcloud第二季分为上半场和下半场"
        },
        {
          "level": 3,
          "title": "Springboot版本选择",
          "slug": "springboot版本选择"
        },
        {
          "level": 3,
          "title": "SpringCloud版本选择",
          "slug": "springcloud版本选择"
        },
        {
          "level": 3,
          "title": "SpringCloud和Springboot之间的依赖关系如何看",
          "slug": "springcloud和springboot之间的依赖关系如何看"
        },
        {
          "level": 3,
          "title": "SpringCloud第二季定稿版（截止2020.2.15）",
          "slug": "springcloud第二季定稿版-截止2020-2-15"
        },
        {
          "level": 2,
          "title": "3.关于Cloud各种组件的停更/升级/替换",
          "slug": "_3-关于cloud各种组件的停更-升级-替换"
        },
        {
          "level": 3,
          "title": "由停更引发的“升级惨案”",
          "slug": "由停更引发的-升级惨案"
        },
        {
          "level": 3,
          "title": "参考资料见官网",
          "slug": "参考资料见官网"
        },
        {
          "level": 2,
          "title": "4.微服务架构编码构建",
          "slug": "_4-微服务架构编码构建"
        },
        {
          "level": 3,
          "title": "约定 > 配置 > 编码",
          "slug": "约定-配置-编码"
        },
        {
          "level": 3,
          "title": "IDEA新建project工作空间",
          "slug": "idea新建project工作空间"
        },
        {
          "level": 3,
          "title": "Rest微服务工程构建",
          "slug": "rest微服务工程构建"
        },
        {
          "level": 2,
          "title": "5.Eureka服务注册与发现",
          "slug": "_5-eureka服务注册与发现"
        },
        {
          "level": 3,
          "title": "Eureka基础知识",
          "slug": "eureka基础知识"
        },
        {
          "level": 3,
          "title": "单机Eureka构建步骤",
          "slug": "单机eureka构建步骤"
        },
        {
          "level": 3,
          "title": "集群Eureka构建步骤",
          "slug": "集群eureka构建步骤"
        },
        {
          "level": 3,
          "title": "actuator微服务信息完善",
          "slug": "actuator微服务信息完善"
        },
        {
          "level": 3,
          "title": "服务发现Discovery",
          "slug": "服务发现discovery"
        },
        {
          "level": 3,
          "title": "Eureka自我保护",
          "slug": "eureka自我保护"
        },
        {
          "level": 2,
          "title": "6.Zookeeper服务注册与发现",
          "slug": "_6-zookeeper服务注册与发现"
        },
        {
          "level": 3,
          "title": "Eureka停止更新了你怎么办",
          "slug": "eureka停止更新了你怎么办"
        },
        {
          "level": 3,
          "title": "SpringCloud整合Zookeeper代替Eureka",
          "slug": "springcloud整合zookeeper代替eureka"
        },
        {
          "level": 2,
          "title": "7.Consul服务注册与发现",
          "slug": "_7-consul服务注册与发现"
        },
        {
          "level": 3,
          "title": "Consul简介",
          "slug": "consul简介"
        },
        {
          "level": 3,
          "title": "安装并运行Consul",
          "slug": "安装并运行consul"
        },
        {
          "level": 3,
          "title": "服务提供者",
          "slug": "服务提供者"
        },
        {
          "level": 3,
          "title": "服务消费者",
          "slug": "服务消费者"
        },
        {
          "level": 3,
          "title": "三个注册中心异同点",
          "slug": "三个注册中心异同点"
        },
        {
          "level": 2,
          "title": "8.Ribbon负载均衡服务调用",
          "slug": "_8-ribbon负载均衡服务调用"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述"
        },
        {
          "level": 3,
          "title": "Ribbon负载均衡演示",
          "slug": "ribbon负载均衡演示"
        },
        {
          "level": 3,
          "title": "Ribbon核心组件IRule",
          "slug": "ribbon核心组件irule"
        },
        {
          "level": 3,
          "title": "Ribbon负载均衡算法",
          "slug": "ribbon负载均衡算法"
        },
        {
          "level": 2,
          "title": "9.OpenFeign服务接口调用",
          "slug": "_9-openfeign服务接口调用"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述-2"
        },
        {
          "level": 3,
          "title": "OpenFeign使用步骤",
          "slug": "openfeign使用步骤"
        },
        {
          "level": 3,
          "title": "OpenFeign超时控制",
          "slug": "openfeign超时控制"
        },
        {
          "level": 3,
          "title": "OpenFeign日志打印功能",
          "slug": "openfeign日志打印功能"
        },
        {
          "level": 2,
          "title": "10.Hystrix断路器",
          "slug": "_10-hystrix断路器"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述-3"
        },
        {
          "level": 3,
          "title": "Hystrix重要概念",
          "slug": "hystrix重要概念"
        },
        {
          "level": 3,
          "title": "hystrix案例",
          "slug": "hystrix案例"
        },
        {
          "level": 3,
          "title": "hystrix工作流程",
          "slug": "hystrix工作流程"
        },
        {
          "level": 3,
          "title": "服务监控hystrixDashboard",
          "slug": "服务监控hystrixdashboard"
        },
        {
          "level": 2,
          "title": "11.zuul路由网关（没讲）",
          "slug": "_11-zuul路由网关-没讲"
        },
        {
          "level": 2,
          "title": "12.Gateway新一代网关",
          "slug": "_12-gateway新一代网关"
        },
        {
          "level": 3,
          "title": "概述简介",
          "slug": "概述简介"
        },
        {
          "level": 3,
          "title": "三大核心概念",
          "slug": "三大核心概念"
        },
        {
          "level": 3,
          "title": "Gateway工作流程",
          "slug": "gateway工作流程"
        },
        {
          "level": 3,
          "title": "入门配置",
          "slug": "入门配置"
        },
        {
          "level": 3,
          "title": "通过微服务名实现动态路由",
          "slug": "通过微服务名实现动态路由"
        },
        {
          "level": 3,
          "title": "Predicate的使用",
          "slug": "predicate的使用"
        },
        {
          "level": 3,
          "title": "Filter的使用",
          "slug": "filter的使用"
        },
        {
          "level": 2,
          "title": "13.SpringCloud config分布式配置中心",
          "slug": "_13-springcloud-config分布式配置中心"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述-4"
        },
        {
          "level": 3,
          "title": "Config服务端配置与测试",
          "slug": "config服务端配置与测试"
        },
        {
          "level": 3,
          "title": "Config客户端配置与测试",
          "slug": "config客户端配置与测试"
        },
        {
          "level": 3,
          "title": "Config客户端之动态刷新",
          "slug": "config客户端之动态刷新"
        },
        {
          "level": 2,
          "title": "14.SpringCloud Bus 消息总线",
          "slug": "_14-springcloud-bus-消息总线"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述-5"
        },
        {
          "level": 3,
          "title": "RabbitMQ环境配置",
          "slug": "rabbitmq环境配置"
        },
        {
          "level": 3,
          "title": "SpringCloud Bus动态刷新全局广播",
          "slug": "springcloud-bus动态刷新全局广播"
        },
        {
          "level": 3,
          "title": "SpringCloud Bus动态刷新定点通知",
          "slug": "springcloud-bus动态刷新定点通知"
        },
        {
          "level": 2,
          "title": "15.SpringCloud Stream消息驱动",
          "slug": "_15-springcloud-stream消息驱动"
        },
        {
          "level": 3,
          "title": "消息驱动概述",
          "slug": "消息驱动概述"
        },
        {
          "level": 3,
          "title": "案例说明",
          "slug": "案例说明"
        },
        {
          "level": 3,
          "title": "消息驱动之生产者",
          "slug": "消息驱动之生产者"
        },
        {
          "level": 3,
          "title": "消息驱动之消费者",
          "slug": "消息驱动之消费者"
        },
        {
          "level": 3,
          "title": "分组消费与持久化",
          "slug": "分组消费与持久化"
        },
        {
          "level": 2,
          "title": "16.SpringCloud Sleuth分布式请求链路追踪",
          "slug": "_16-springcloud-sleuth分布式请求链路追踪"
        },
        {
          "level": 3,
          "title": "概述",
          "slug": "概述-6"
        },
        {
          "level": 3,
          "title": "搭建链路监控步骤",
          "slug": "搭建链路监控步骤"
        },
        {
          "level": 2,
          "title": "17.SpringCloud Alibaba入门简介",
          "slug": "_17-springcloud-alibaba入门简介"
        },
        {
          "level": 3,
          "title": "why会出现SpringCloud alibaba",
          "slug": "why会出现springcloud-alibaba"
        },
        {
          "level": 3,
          "title": "SpringCloud alibaba带来了什么？",
          "slug": "springcloud-alibaba带来了什么"
        },
        {
          "level": 3,
          "title": "SpringCloud alibaba学习资料获取",
          "slug": "springcloud-alibaba学习资料获取"
        },
        {
          "level": 2,
          "title": "18.SpringCloud Alibaba Nacos服务注册和配置中心",
          "slug": "_18-springcloud-alibaba-nacos服务注册和配置中心"
        },
        {
          "level": 3,
          "title": "Nacos简介",
          "slug": "nacos简介"
        },
        {
          "level": 3,
          "title": "安装并运行Nacos",
          "slug": "安装并运行nacos"
        },
        {
          "level": 3,
          "title": "Nacos作为服务注册中心演示",
          "slug": "nacos作为服务注册中心演示"
        },
        {
          "level": 3,
          "title": "Nacos作为服务配置中心演示",
          "slug": "nacos作为服务配置中心演示"
        },
        {
          "level": 3,
          "title": "Nacos集群和持久化配置（重要）",
          "slug": "nacos集群和持久化配置-重要"
        },
        {
          "level": 2,
          "title": "19.SpringCloud Alibaba Sentinel实现熔断与限流",
          "slug": "_19-springcloud-alibaba-sentinel实现熔断与限流"
        },
        {
          "level": 3,
          "title": "Sentinel",
          "slug": "sentinel"
        },
        {
          "level": 3,
          "title": "安装Sentinel控制台",
          "slug": "安装sentinel控制台"
        },
        {
          "level": 3,
          "title": "初始化演示工程",
          "slug": "初始化演示工程"
        },
        {
          "level": 3,
          "title": "流控规则",
          "slug": "流控规则"
        },
        {
          "level": 3,
          "title": "降级规则",
          "slug": "降级规则"
        },
        {
          "level": 3,
          "title": "热点key限流",
          "slug": "热点key限流"
        },
        {
          "level": 3,
          "title": "系统规则",
          "slug": "系统规则"
        },
        {
          "level": 3,
          "title": "@SentinelResource",
          "slug": "sentinelresource"
        },
        {
          "level": 3,
          "title": "服务熔断功能",
          "slug": "服务熔断功能"
        },
        {
          "level": 3,
          "title": "规则持久化",
          "slug": "规则持久化"
        },
        {
          "level": 2,
          "title": "20.SpringCloud Alibaba Seata处理分布式事务",
          "slug": "_20-springcloud-alibaba-seata处理分布式事务"
        },
        {
          "level": 3,
          "title": "分布式事务问题",
          "slug": "分布式事务问题"
        },
        {
          "level": 3,
          "title": "Seata简介",
          "slug": "seata简介"
        },
        {
          "level": 3,
          "title": "Seata-Server安装",
          "slug": "seata-server安装"
        },
        {
          "level": 3,
          "title": "订单/库存/账户业务数据库准备",
          "slug": "订单-库存-账户业务数据库准备"
        },
        {
          "level": 3,
          "title": "订单/库存/账户业务微服务准备",
          "slug": "订单-库存-账户业务微服务准备"
        },
        {
          "level": 3,
          "title": "Test",
          "slug": "test"
        },
        {
          "level": 3,
          "title": "Seata之原理简介",
          "slug": "seata之原理简介"
        }
      ]
    },
    {
      "title": "Nacos",
      "frontmatter": {},
      "regularPath": "/blog/Java-Frame/nacos.html",
      "relativePath": "blog/Java-Frame/nacos.md",
      "key": "v-af354208",
      "path": "/blog/Java-Frame/nacos.html",
      "headers": [
        {
          "level": 2,
          "title": "入门",
          "slug": "入门"
        }
      ]
    },
    {
      "title": "MQ",
      "frontmatter": {},
      "regularPath": "/blog/Java-Frame/mq.html",
      "relativePath": "blog/Java-Frame/mq.md",
      "key": "v-0a9953c0",
      "path": "/blog/Java-Frame/mq.html",
      "headers": [
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 3,
          "title": "启动：(暂时)",
          "slug": "启动-暂时"
        },
        {
          "level": 2,
          "title": "安装配置",
          "slug": "安装配置"
        },
        {
          "level": 2,
          "title": "常见错误",
          "slug": "常见错误"
        }
      ]
    },
    {
      "title": "Apollo",
      "frontmatter": {},
      "regularPath": "/blog/Java-Frame/apollo.html",
      "relativePath": "blog/Java-Frame/apollo.md",
      "key": "v-12fea34a",
      "path": "/blog/Java-Frame/apollo.html",
      "headers": [
        {
          "level": 2,
          "title": "入门",
          "slug": "入门"
        }
      ]
    },
    {
      "title": "Tomcat 安装/服务启动与关闭",
      "frontmatter": {},
      "regularPath": "/blog/Java-Frame/Tomcat/Tomcat-Init.html",
      "relativePath": "blog/Java-Frame/Tomcat/Tomcat-Init.md",
      "key": "v-0485fdcc",
      "path": "/blog/Java-Frame/Tomcat/Tomcat-Init.html",
      "headers": [
        {
          "level": 2,
          "title": "Linux ContOS7 安装 Tomcat9",
          "slug": "linux-contos7-安装-tomcat9"
        }
      ]
    },
    {
      "title": "文件处理",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Common-file.html",
      "relativePath": "blog/Java/Common/Common-file.md",
      "key": "v-5c24bff4",
      "path": "/blog/Java/Common/Common-file.html",
      "headers": [
        {
          "level": 2,
          "title": "读取txt文件",
          "slug": "读取txt文件"
        },
        {
          "level": 3,
          "title": "读取全部文件",
          "slug": "读取全部文件"
        }
      ]
    },
    {
      "title": "package-info.java的使用",
      "frontmatter": {},
      "regularPath": "/blog/Java/Annotation/package-info.html",
      "relativePath": "blog/Java/Annotation/package-info.md",
      "key": "v-705bcb48",
      "path": "/blog/Java/Annotation/package-info.html",
      "headers": [
        {
          "level": 2,
          "title": "场景",
          "slug": "场景"
        },
        {
          "level": 2,
          "title": "创建package-info.java",
          "slug": "创建package-info-java"
        },
        {
          "level": 2,
          "title": "package-info.java的使用",
          "slug": "package-info-java的使用-2"
        }
      ]
    },
    {
      "title": "Nginx",
      "frontmatter": {},
      "regularPath": "/blog/Java-Frame/nginx.html",
      "relativePath": "blog/Java-Frame/nginx.md",
      "key": "v-b1dc9f88",
      "path": "/blog/Java-Frame/nginx.html",
      "headers": [
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "思路",
          "slug": "思路"
        },
        {
          "level": 3,
          "title": "修改 nginx 的默认端口",
          "slug": "修改-nginx-的默认端口"
        }
      ]
    },
    {
      "title": "fastjson - 自定义反序列化",
      "frontmatter": {},
      "regularPath": "/blog/Java/FastJson/Fastjson-Deserialize.html",
      "relativePath": "blog/Java/FastJson/Fastjson-Deserialize.md",
      "key": "v-b11c2dc8",
      "path": "/blog/Java/FastJson/Fastjson-Deserialize.html",
      "headers": [
        {
          "level": 2,
          "title": "场景",
          "slug": "场景"
        },
        {
          "level": 2,
          "title": "自定义反序列化解析器 - ObjectDeserializer",
          "slug": "自定义反序列化解析器-objectdeserializer"
        },
        {
          "level": 2,
          "title": "使用解析器",
          "slug": "使用解析器"
        }
      ]
    },
    {
      "title": "JSONField与JSONType注解的使用",
      "frontmatter": {},
      "regularPath": "/blog/Java/FastJson/Fastjson-JSONField-JSONType.html",
      "relativePath": "blog/Java/FastJson/Fastjson-JSONField-JSONType.md",
      "key": "v-58efd072",
      "path": "/blog/Java/FastJson/Fastjson-JSONField-JSONType.html",
      "headers": [
        {
          "level": 2,
          "title": "@JSONField",
          "slug": "jsonfield"
        },
        {
          "level": 2,
          "title": "@JSONType",
          "slug": "jsontype"
        }
      ]
    },
    {
      "title": "排序",
      "frontmatter": {},
      "regularPath": "/blog/Java/Common/Common-sort.html",
      "relativePath": "blog/Java/Common/Common-sort.md",
      "key": "v-42965230",
      "path": "/blog/Java/Common/Common-sort.html",
      "headers": [
        {
          "level": 2,
          "title": "Java 8 Comparator: 列表排序",
          "slug": "java-8-comparator-列表排序"
        },
        {
          "level": 3,
          "title": "1.按字母顺序排序字符串列表",
          "slug": "_1-按字母顺序排序字符串列表"
        },
        {
          "level": 3,
          "title": "2.对整数列表进行排序",
          "slug": "_2-对整数列表进行排序"
        },
        {
          "level": 3,
          "title": "3.按字符串字段对列表进行排序",
          "slug": "_3-按字符串字段对列表进行排序"
        },
        {
          "level": 3,
          "title": "4.按Double字段排序列表",
          "slug": "_4-按double字段排序列表"
        },
        {
          "level": 3,
          "title": "5.使用自定义比较器对列表进行排序",
          "slug": "_5-使用自定义比较器对列表进行排序"
        },
        {
          "level": 3,
          "title": "6.使用比较器链对列表进行排序",
          "slug": "_6-使用比较器链对列表进行排序"
        }
      ]
    },
    {
      "title": "fastjson - 自定义序列化",
      "frontmatter": {},
      "regularPath": "/blog/Java/FastJson/Fastjson-Serialize.html",
      "relativePath": "blog/Java/FastJson/Fastjson-Serialize.md",
      "key": "v-01a4e188",
      "path": "/blog/Java/FastJson/Fastjson-Serialize.html",
      "headers": [
        {
          "level": 2,
          "title": "场景",
          "slug": "场景"
        },
        {
          "level": 2,
          "title": "自定义反序列化解析器 - ObjectSerializer",
          "slug": "自定义反序列化解析器-objectserializer"
        },
        {
          "level": 2,
          "title": "使用解析器",
          "slug": "使用解析器"
        },
        {
          "level": 2,
          "title": "序列化相关的概念",
          "slug": "序列化相关的概念"
        }
      ]
    },
    {
      "title": "SerializeFilter",
      "frontmatter": {},
      "regularPath": "/blog/Java/FastJson/Fastjson-SerializeFilter.html",
      "relativePath": "blog/Java/FastJson/Fastjson-SerializeFilter.md",
      "key": "v-175d2bbc",
      "path": "/blog/Java/FastJson/Fastjson-SerializeFilter.html"
    },
    {
      "title": "Fastjson - SerializerFeature特性的使用",
      "frontmatter": {},
      "regularPath": "/blog/Java/FastJson/Fastjson-SerializerFeature.html",
      "relativePath": "blog/Java/FastJson/Fastjson-SerializerFeature.md",
      "key": "v-3f473688",
      "path": "/blog/Java/FastJson/Fastjson-SerializerFeature.html"
    },
    {
      "title": "Fastjson 使用",
      "frontmatter": {},
      "regularPath": "/blog/Java/FastJson/Fastjson-Use.html",
      "relativePath": "blog/Java/FastJson/Fastjson-Use.md",
      "key": "v-f41999c8",
      "path": "/blog/Java/FastJson/Fastjson-Use.html"
    },
    {
      "title": "接口开发",
      "frontmatter": {},
      "regularPath": "/blog/Java/Interface.html",
      "relativePath": "blog/Java/Interface.md",
      "key": "v-574bf09c",
      "path": "/blog/Java/Interface.html",
      "headers": [
        {
          "level": 2,
          "title": "注解",
          "slug": "注解"
        },
        {
          "level": 3,
          "title": "@RestController",
          "slug": "restcontroller"
        },
        {
          "level": 3,
          "title": "@PathVariable",
          "slug": "pathvariable"
        }
      ]
    },
    {
      "title": "集合",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Collection.html",
      "relativePath": "blog/Java/Java-Collection.md",
      "key": "v-0fc8da48",
      "path": "/blog/Java/Java-Collection.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是集合",
          "slug": "什么是集合"
        },
        {
          "level": 2,
          "title": "Collection体系",
          "slug": "collection体系"
        },
        {
          "level": 2,
          "title": "泛型",
          "slug": "泛型"
        },
        {
          "level": 2,
          "title": "Set集合",
          "slug": "set集合"
        },
        {
          "level": 2,
          "title": "Map",
          "slug": "map"
        },
        {
          "level": 2,
          "title": "Collection工具类",
          "slug": "collection工具类"
        }
      ]
    },
    {
      "title": "Java常见语法",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Common.html",
      "relativePath": "blog/Java/Java-Common.md",
      "key": "v-063440bc",
      "path": "/blog/Java/Java-Common.html"
    },
    {
      "title": "Swagger API",
      "frontmatter": {},
      "regularPath": "/blog/Java/Swagger.html",
      "relativePath": "blog/Java/Swagger.md",
      "key": "v-2947893c",
      "path": "/blog/Java/Swagger.html"
    },
    {
      "title": "常用工具包",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-Toolkit.html",
      "relativePath": "blog/Java/Java-Toolkit.md",
      "key": "v-cf3b107c",
      "path": "/blog/Java/Java-Toolkit.html"
    },
    {
      "title": "list常用语法",
      "frontmatter": {},
      "regularPath": "/blog/Java/Java-list.html",
      "relativePath": "blog/Java/Java-list.md",
      "key": "v-eaf132c8",
      "path": "/blog/Java/Java-list.html",
      "headers": [
        {
          "level": 2,
          "title": "java8List.sort()排序功能",
          "slug": "java8list-sort-排序功能"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Live-Stream/SRS.html",
      "relativePath": "blog/Live-Stream/SRS.md",
      "key": "v-17a98614",
      "path": "/blog/Live-Stream/SRS.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "主要思想",
          "slug": "主要思想"
        },
        {
          "level": 2,
          "title": "常见语法",
          "slug": "常见语法"
        },
        {
          "level": 2,
          "title": "常见问题",
          "slug": "常见问题"
        }
      ]
    },
    {
      "title": "AR",
      "frontmatter": {},
      "regularPath": "/blog/Live-Stream/AR.html",
      "relativePath": "blog/Live-Stream/AR.md",
      "key": "v-4e49d5fc",
      "path": "/blog/Live-Stream/AR.html",
      "headers": [
        {
          "level": 2,
          "title": "AR事例",
          "slug": "ar事例"
        },
        {
          "level": 3,
          "title": "JS快速实验室: 手势控制3D物体",
          "slug": "js快速实验室-手势控制3d物体"
        },
        {
          "level": 3,
          "title": "以实现摄像头精确追踪并识别十指的运动路径/轨迹和手势动作",
          "slug": "以实现摄像头精确追踪并识别十指的运动路径-轨迹和手势动作"
        },
        {
          "level": 3,
          "title": "Handrack.js实现手部识别（手部框）",
          "slug": "handrack-js实现手部识别-手部框"
        },
        {
          "level": 3,
          "title": "可交互内容玩法技术揭秘",
          "slug": "可交互内容玩法技术揭秘"
        },
        {
          "level": 3,
          "title": "Tensorflow JS可识别剪刀石头布三种手势（语言：react+python）",
          "slug": "tensorflow-js可识别剪刀石头布三种手势-语言-react-python"
        },
        {
          "level": 3,
          "title": "Tensorflow 实现手势识别思路",
          "slug": "tensorflow-实现手势识别思路"
        },
        {
          "level": 3,
          "title": "标星 2.3k+，比个手势，AI 自动识别 Emoji！(语言：)",
          "slug": "标星-2-3k-比个手势-ai-自动识别-emoji-语言"
        },
        {
          "level": 2,
          "title": "SDK",
          "slug": "sdk"
        },
        {
          "level": 3,
          "title": "百度AI开发平台",
          "slug": "百度ai开发平台"
        },
        {
          "level": 3,
          "title": "火山引擎",
          "slug": "火山引擎"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Live-Stream/WebSocket.html",
      "relativePath": "blog/Live-Stream/WebSocket.md",
      "key": "v-28d93450",
      "path": "/blog/Live-Stream/WebSocket.html"
    },
    {
      "title": "JavaCV",
      "frontmatter": {},
      "regularPath": "/blog/Live-Stream/JavaCV.html",
      "relativePath": "blog/Live-Stream/JavaCV.md",
      "key": "v-2869547c",
      "path": "/blog/Live-Stream/JavaCV.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Markdown/Markdown.html",
      "relativePath": "blog/Markdown/Markdown.md",
      "key": "v-58da28b8",
      "path": "/blog/Markdown/Markdown.html",
      "headers": [
        {
          "level": 2,
          "title": "Markdown 引用语法",
          "slug": "markdown-引用语法"
        },
        {
          "level": 3,
          "title": "多个段落的块引用",
          "slug": "多个段落的块引用"
        },
        {
          "level": 3,
          "title": "嵌套块引用",
          "slug": "嵌套块引用"
        },
        {
          "level": 3,
          "title": "带有其它元素的块引用",
          "slug": "带有其它元素的块引用"
        },
        {
          "level": 2,
          "title": "Markdown 图片语法",
          "slug": "markdown-图片语法"
        },
        {
          "level": 2,
          "title": "上划线、中划线、下划线",
          "slug": "上划线、中划线、下划线"
        },
        {
          "level": 3,
          "title": "中划线",
          "slug": "中划线"
        },
        {
          "level": 3,
          "title": "下划线",
          "slug": "下划线"
        },
        {
          "level": 3,
          "title": "上划线",
          "slug": "上划线"
        },
        {
          "level": 2,
          "title": "列表",
          "slug": "列表"
        }
      ]
    },
    {
      "title": "Markdown 流程图",
      "frontmatter": {},
      "regularPath": "/blog/Markdown/Markdown-Flowchart.html",
      "relativePath": "blog/Markdown/Markdown-Flowchart.md",
      "key": "v-3501a244",
      "path": "/blog/Markdown/Markdown-Flowchart.html",
      "headers": [
        {
          "level": 3,
          "title": "示例",
          "slug": "示例"
        }
      ]
    },
    {
      "title": "银河麒麟",
      "frontmatter": {},
      "regularPath": "/blog/OS/Kylin.html",
      "relativePath": "blog/OS/Kylin.md",
      "key": "v-79a9ea48",
      "path": "/blog/OS/Kylin.html",
      "headers": [
        {
          "level": 3,
          "title": "银河麒麟安装达梦数据库",
          "slug": "银河麒麟安装达梦数据库"
        },
        {
          "level": 2,
          "title": "银河麒麟kylin使用root用户登录方法",
          "slug": "银河麒麟kylin使用root用户登录方法"
        },
        {
          "level": 3,
          "title": "银河麒麟4.0.2桌面版（arm平台）搭建Tomcat+Apache+nginx 环境",
          "slug": "银河麒麟4-0-2桌面版-arm平台-搭建tomcat-apache-nginx-环境"
        }
      ]
    },
    {
      "title": "Linux",
      "frontmatter": {},
      "regularPath": "/blog/OS/Linux.html",
      "relativePath": "blog/OS/Linux.md",
      "key": "v-ae2b6a88",
      "path": "/blog/OS/Linux.html",
      "headers": [
        {
          "level": 2,
          "title": "§ 查看网卡信息（获取ip）",
          "slug": "§-查看网卡信息-获取ip"
        },
        {
          "level": 3,
          "title": "Linux文件夹创建",
          "slug": "linux文件夹创建"
        },
        {
          "level": 3,
          "title": "Linux将文件复制粘贴到另外一个位置",
          "slug": "linux将文件复制粘贴到另外一个位置"
        },
        {
          "level": 3,
          "title": "Linux切换用户",
          "slug": "linux切换用户"
        },
        {
          "level": 3,
          "title": "在 Ubuntu（16.04）中使用 APT 安装 MySQL（5.7.25）",
          "slug": "在-ubuntu-16-04-中使用-apt-安装-mysql-5-7-25"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/OS/Mac.html",
      "relativePath": "blog/OS/Mac.md",
      "key": "v-dfff36c8",
      "path": "/blog/OS/Mac.html"
    },
    {
      "title": "黑盒测试与白盒测试",
      "frontmatter": {},
      "regularPath": "/blog/Testing/Test-Common/Blackbox-Whitebox.html",
      "relativePath": "blog/Testing/Test-Common/Blackbox-Whitebox.md",
      "key": "v-785f678c",
      "path": "/blog/Testing/Test-Common/Blackbox-Whitebox.html",
      "headers": [
        {
          "level": 2,
          "title": "第一认识",
          "slug": "第一认识"
        },
        {
          "level": 3,
          "title": "黑盒测试",
          "slug": "黑盒测试"
        },
        {
          "level": 3,
          "title": "白盒测试",
          "slug": "白盒测试"
        },
        {
          "level": 2,
          "title": "第二认识",
          "slug": "第二认识"
        },
        {
          "level": 3,
          "title": "黑盒测试",
          "slug": "黑盒测试-2"
        },
        {
          "level": 3,
          "title": "白盒测试",
          "slug": "白盒测试-2"
        },
        {
          "level": 2,
          "title": "第三认识",
          "slug": "第三认识"
        },
        {
          "level": 3,
          "title": "黑盒测试",
          "slug": "黑盒测试-3"
        },
        {
          "level": 3,
          "title": "白盒测试",
          "slug": "白盒测试-3"
        }
      ]
    },
    {
      "title": "虚拟机",
      "frontmatter": {},
      "regularPath": "/blog/OS/Virtual-Machine.html",
      "relativePath": "blog/OS/Virtual-Machine.md",
      "key": "v-0e780248",
      "path": "/blog/OS/Virtual-Machine.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        }
      ]
    },
    {
      "title": "断言",
      "frontmatter": {},
      "regularPath": "/blog/Testing/Test-Common/Test-Assert.html",
      "relativePath": "blog/Testing/Test-Common/Test-Assert.md",
      "key": "v-edab2660",
      "path": "/blog/Testing/Test-Common/Test-Assert.html",
      "headers": [
        {
          "level": 2,
          "title": "编写断言的表达式",
          "slug": "编写断言的表达式"
        },
        {
          "level": 3,
          "title": "举个例子",
          "slug": "举个例子"
        },
        {
          "level": 2,
          "title": "运行后没有反应??",
          "slug": "运行后没有反应"
        },
        {
          "level": 2,
          "title": "希望获得更多信息?",
          "slug": "希望获得更多信息"
        },
        {
          "level": 3,
          "title": "举个例子",
          "slug": "举个例子-2"
        },
        {
          "level": 2,
          "title": "前置条件和后置条件",
          "slug": "前置条件和后置条件"
        },
        {
          "level": 3,
          "title": "前置条件",
          "slug": "前置条件"
        },
        {
          "level": 3,
          "title": "后置条件",
          "slug": "后置条件"
        },
        {
          "level": 2,
          "title": "陷阱",
          "slug": "陷阱"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "TestNG 基本注解",
      "frontmatter": {},
      "regularPath": "/blog/Testing/TestNG/TestNG-Annotation.html",
      "relativePath": "blog/Testing/TestNG/TestNG-Annotation.md",
      "key": "v-160b5d5c",
      "path": "/blog/Testing/TestNG/TestNG-Annotation.html",
      "headers": [
        {
          "level": 2,
          "title": "使用注释/注解的好处",
          "slug": "使用注释-注解的好处"
        }
      ]
    },
    {
      "title": "测试相关概念梳理",
      "frontmatter": {},
      "regularPath": "/blog/Testing/Test-Common/Test-Init.html",
      "relativePath": "blog/Testing/Test-Common/Test-Init.md",
      "key": "v-00e8513c",
      "path": "/blog/Testing/Test-Common/Test-Init.html"
    },
    {
      "title": "CSS",
      "frontmatter": {},
      "regularPath": "/blog/Web/CSS/CSS.html",
      "relativePath": "blog/Web/CSS/CSS.md",
      "key": "v-ad67ce6c",
      "path": "/blog/Web/CSS/CSS.html",
      "headers": [
        {
          "level": 2,
          "title": "常见场景",
          "slug": "常见场景"
        }
      ]
    },
    {
      "title": "TestNG - DataProvider（注解）数据提供者",
      "frontmatter": {},
      "regularPath": "/blog/Testing/TestNG/TestNG-DataProvider.html",
      "relativePath": "blog/Testing/TestNG/TestNG-DataProvider.md",
      "key": "v-2950a8c8",
      "path": "/blog/Testing/TestNG/TestNG-DataProvider.html",
      "headers": [
        {
          "level": 2,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 2,
          "title": "备注",
          "slug": "备注"
        },
        {
          "level": 3,
          "title": "注解使用",
          "slug": "注解使用"
        },
        {
          "level": 3,
          "title": "返回结构Object[][]",
          "slug": "返回结构object"
        },
        {
          "level": 2,
          "title": "提供数据方式",
          "slug": "提供数据方式"
        }
      ]
    },
    {
      "title": "TestNG 使用",
      "frontmatter": {},
      "regularPath": "/blog/Testing/TestNG/TestNG-Init.html",
      "relativePath": "blog/Testing/TestNG/TestNG-Init.md",
      "key": "v-d23a1e88",
      "path": "/blog/Testing/TestNG/TestNG-Init.html",
      "headers": [
        {
          "level": 2,
          "title": "maven",
          "slug": "maven"
        },
        {
          "level": 2,
          "title": "概念",
          "slug": "概念"
        }
      ]
    },
    {
      "title": "可参考内容",
      "frontmatter": {},
      "regularPath": "/blog/Web/Android/Reference.html",
      "relativePath": "blog/Web/Android/Reference.md",
      "key": "v-2a32d3bc",
      "path": "/blog/Web/Android/Reference.html"
    },
    {
      "title": "vuepress",
      "frontmatter": {},
      "regularPath": "/blog/Web/Vue/Vuepress.html",
      "relativePath": "blog/Web/Vue/Vuepress.md",
      "key": "v-175829bc",
      "path": "/blog/Web/Vue/Vuepress.html",
      "headers": [
        {
          "level": 2,
          "title": "基础了解",
          "slug": "基础了解"
        },
        {
          "level": 2,
          "title": "遇见过的问题",
          "slug": "遇见过的问题"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/blog/Web/Vue/Vue.html",
      "relativePath": "blog/Web/Vue/Vue.md",
      "key": "v-d38cf784",
      "path": "/blog/Web/Vue/Vue.html"
    },
    {
      "title": "vscode",
      "frontmatter": {},
      "regularPath": "/blog/Web/IDE/VSCode.html",
      "relativePath": "blog/Web/IDE/VSCode.md",
      "key": "v-bec16b48",
      "path": "/blog/Web/IDE/VSCode.html"
    },
    {
      "title": "ES6的export与Nodejs的module.exports",
      "frontmatter": {},
      "regularPath": "/blog/Web/JS/JS-Module-Specification.html",
      "relativePath": "blog/Web/JS/JS-Module-Specification.md",
      "key": "v-7747d57c",
      "path": "/blog/Web/JS/JS-Module-Specification.html",
      "headers": [
        {
          "level": 2,
          "title": "CommonJS模块规范",
          "slug": "commonjs模块规范"
        },
        {
          "level": 3,
          "title": "exports 与 module.exports",
          "slug": "exports-与-module-exports"
        },
        {
          "level": 2,
          "title": "ES6模块规范",
          "slug": "es6模块规范"
        },
        {
          "level": 3,
          "title": "export default 命令",
          "slug": "export-default-命令"
        }
      ]
    },
    {
      "title": "分布式",
      "frontmatter": {},
      "regularPath": "/blog/%E6%A6%82%E5%BF%B5%E6%A2%B3%E7%90%86.html",
      "relativePath": "blog/概念梳理.md",
      "key": "v-d038b8de",
      "path": "/blog/%E6%A6%82%E5%BF%B5%E6%A2%B3%E7%90%86.html",
      "headers": [
        {
          "level": 2,
          "title": "分布式",
          "slug": "分布式"
        },
        {
          "level": 2,
          "title": "微服务",
          "slug": "微服务"
        },
        {
          "level": 2,
          "title": "SAAS",
          "slug": "saas"
        }
      ]
    },
    {
      "title": "Fiddler 抓包工具",
      "frontmatter": {},
      "regularPath": "/blog/%E4%B8%B4%E6%97%B6%E5%AD%98%E5%82%A8/%E6%8A%93%E5%8C%85%E5%B7%A5%E5%85%B7%20Fiddler/Fiddler.html",
      "relativePath": "blog/临时存储/抓包工具 Fiddler/Fiddler.md",
      "key": "v-da79eb82",
      "path": "/blog/%E4%B8%B4%E6%97%B6%E5%AD%98%E5%82%A8/%E6%8A%93%E5%8C%85%E5%B7%A5%E5%85%B7%20Fiddler/Fiddler.html"
    }
  ],
  "themeConfig": {
    "repo": "https://github.com/guoshunfa/document-backup",
    "repoLabel": "GitHub",
    "sidebar": "auto",
    "nav": [
      {
        "text": "Java",
        "items": [
          {
            "text": "接口设计",
            "items": [
              {
                "text": "接口定义",
                "link": "/blog/Java/Interface/"
              }
            ]
          },
          {
            "text": "Fastjson",
            "items": [
              {
                "text": "Fastjson 使用",
                "link": "/blog/Java/FastJson/Fastjson-Use"
              },
              {
                "text": "Fastjson 自定义序列化",
                "link": "/blog/Java/FastJson/Fastjson-Serialize"
              },
              {
                "text": "Fastjson 自定义反序列化",
                "link": "/blog/Java/FastJson/Fastjson-Deserialize"
              },
              {
                "text": "Fastjson SerializerFeature特性的使用",
                "link": "/blog/Java/FastJson/Fastjson-SerializerFeature"
              },
              {
                "text": "Fastjson JSONField与JSONType注解的使用",
                "link": "/blog/Java/FastJson/Fastjson-JSONField-JSONType"
              }
            ]
          },
          {
            "text": "@ @",
            "items": [
              {
                "text": "工具包",
                "link": "/blog/java/Java-Toolkit/"
              }
            ]
          }
        ]
      },
      {
        "text": "Java 框架/组件",
        "items": [
          {
            "text": "Spring",
            "items": [
              {
                "text": "Spring Event",
                "link": "/blog/Java-Frame/Spring/Spring-Event"
              },
              {
                "text": "Spring 校验器（Validator）",
                "link": "/blog/Java-Frame/Spring/Spring-Validator"
              }
            ]
          },
          {
            "text": "Tomcat",
            "items": [
              {
                "text": "Tomcat 安装/服务启动与暂停",
                "link": "/blog/Java-Frame/Tomcat/Tomcat-Init"
              },
              {
                "text": "Tomcat 启动web项目",
                "link": "/blog/Java-Frame/Tomcat/Tomcat-Web"
              }
            ]
          },
          {
            "text": "IDE",
            "items": [
              {
                "text": "IDEA 使用说明",
                "link": "/blog/Java-Frame/IDE/IDEA"
              }
            ]
          }
        ]
      },
      {
        "text": "数据库",
        "items": [
          {
            "text": "MongoDB",
            "items": [
              {
                "text": "MongoDB 安装/服务暂停和启动",
                "link": "/blog/Database/MongoDB/MongoDB-Init"
              },
              {
                "text": "MongoDB Shell语法",
                "link": "/blog/Database/MongoDB/MongoDB-Shell"
              },
              {
                "text": "MongoDB 执行JS脚本",
                "link": "/blog/Database/MongoDB/MongoDB-Script"
              }
            ]
          },
          {
            "text": "Mysql",
            "items": [
              {
                "text": "Mysql 安装/服务暂停和启动",
                "link": "/blog/Database/Mysql/Mysql-Init"
              },
              {
                "text": "Mysql sql使用说明",
                "link": "/blog/Database/Mysql/Mysql-SQL"
              },
              {
                "text": "Mysql 可视化软件Workbench使用说明",
                "link": "/blog/Database/Mysql/Mysql-Workbench"
              },
              {
                "text": "Mysql 控制台使用说明",
                "link": "/blog/Database/Mysql/Mysql-Console"
              },
              {
                "text": "Mysql 常见错误",
                "link": "/blog/Database/Mysql/Mysql-Error"
              }
            ]
          },
          {
            "text": "Redis",
            "items": [
              {
                "text": "Redis 安装/服务暂停和启动",
                "link": "/blog/Database/Redis/Redis-Init"
              }
            ]
          },
          {
            "text": "达梦数据库",
            "items": [
              {
                "text": "达梦数据库",
                "link": "/blog/Database/DM/DM/"
              }
            ]
          }
        ]
      },
      {
        "text": "Web",
        "items": [
          {
            "text": "JS",
            "items": [
              {
                "text": "JS模块规范",
                "link": "/blog/Web/JS/JS-Module-Specification/"
              }
            ]
          },
          {
            "text": "CSS",
            "items": [
              {
                "text": "CSS",
                "link": "/blog/Web/CSS/CSS/"
              }
            ]
          },
          {
            "text": "Vue",
            "items": [
              {
                "text": "Vue",
                "link": "/blog/Web/Vue/Vue/"
              },
              {
                "text": "Vuepress",
                "link": "/blog/Web/Vue/Vuepress/"
              }
            ]
          },
          {
            "text": "IDE",
            "items": [
              {
                "text": "VSCode",
                "link": "/blog/Web/IDE/VSCode/"
              }
            ]
          },
          {
            "text": "Android",
            "items": [
              {
                "text": "Android 参考",
                "link": "/blog/Web/Android/Reference/"
              }
            ]
          }
        ]
      },
      {
        "text": "流媒体直播",
        "items": [
          {
            "text": "SRS流媒体直播",
            "link": "/blog/Live-Stream/SRS/"
          },
          {
            "text": "WebSocket",
            "link": "/blog/Live-Stream/WebSocket/"
          },
          {
            "text": "AR",
            "link": "/blog/Live-Stream/AR/"
          },
          {
            "text": "JavaCV",
            "link": "/blog/Live-Stream/JavaCV/"
          }
        ]
      },
      {
        "text": "Markdown",
        "items": [
          {
            "text": "Markdown 常用语法使用说明",
            "link": "/blog/Markdown/Markdown/"
          },
          {
            "text": "Markdown 流程图",
            "link": "/blog/Markdown/Markdown-Flowchart/"
          }
        ]
      },
      {
        "text": "操作系统",
        "items": [
          {
            "text": "Linux",
            "link": "/blog/OS/Linux/"
          },
          {
            "text": "Mac",
            "link": "/blog/OS/Mac/"
          },
          {
            "text": "虚拟机",
            "link": "/blog/OS/Virtual-Machine/"
          },
          {
            "text": "银河麒麟",
            "link": "/blog/OS/Kylin/"
          }
        ]
      }
    ]
  }
}